### ISSUE TITLE
In CI the `test` workflow shouldn't run if the `build` workflow fails

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#1011]
The `test` workflow can take ~10 mins to run and it blocks other workflows from running. It's pointless to run the tests if the build fails.

**Comment by SimonMarquis** [comment]
I've pointed this out in https://github.com/android/nowinandroid/pull/876#discussion_r1284997147, but @JoseAlcerreca thought this would be more useful to get an early feedback https://github.com/android/nowinandroid/pull/876#discussion_r1297342084. Not sure if this is really that useful in practice though.

**Comment by JoseAlcerreca** [comment]
> it blocks other workflows from running

The test and build workflows run in parallel, so we're building part of the app twice, but getting feedback much earlier.

**Comment by SimonMarquis** [comment]
We probably should choose the same approach for both `test` and `androidTest` jobs, what do you think?

![Screenshot_20231103-102737.png](https://github.com/android/nowinandroid/assets/1921278/60e4374e-9fae-4f8e-b15f-cd7eb4a6d873)

**Comment by JoseAlcerreca** [comment]
How?

**Comment by SimonMarquis** [comment]
- make them both `needs: build` and reduce the total usage of resources in case of build errors
- make them both independent, and benefit from early feedback 
- or we keep them as-is and add a comment on the `Build.yaml` to make it clear why different solutions were chosen

**Comment by JoseAlcerreca** [comment]
Sorry I'm not following. It's not clear what you mean by "both". 
Making `test` depend on `build` would delay the `test` feedback by 8 minutes, although it would make test faster, but not 8 minutes faster as it runs in 6. This is because `build` builds things that `test` doesn't need. 

If by "both" you mean `androidTest`s, they already depend on build.

I think the comment "# needs the build result to avoid wasting resources" is unnecessary as it's obvious that you need to build before running the instrumented tests.

**Comment by SimonMarquis** [comment]
> It's not clear what you mean by "both".

both `test` and `androidTest` jobs.

If we chose to run the `test` job independently from the main `build` job to get early feedback, then the same reasoning could be said about the `androidTest` job.

Also, maybe the job name makes it even more confusing because unit tests are already executed in the `build` job, which makes them run twice per workflow. 🤔

**Comment by SimonMarquis** [comment]
> I think the comment "# needs the build result to avoid wasting resources" is unnecessary as it's obvious that you need to build before running the instrumented tests.

No, this is not true. Jobs are run on different machines. When invoking the Gradle task on the `androidTest` job, everything starts from scratch (unless we share build outputs).

**Comment by JoseAlcerreca** [comment]
I see what you mean. I just created the `test` workflow so assumed that build+androidTest was configured correctly, but it's not.

I'd say `build` should happen on macos, and the output should be shared with the two androidTest jobs so they don't start from scratch and if we see a failure we can quickly figure out it it was build-related or androidTest-related.

**Comment by SimonMarquis** [comment]
> assumed that build+androidTest was configured correctly

How so? It is not necessarily incorrectly configured. It was initially configured to only run the androidTest Gradle tasks (only for the modules that need it), and precent running 2x20min of emulators if there was a build (or unit-test) error.

> I'd say build should happen on macos

I would personally advise against that. The build does not need any macos specific feature, and macos has a 10x multiplier on free tier pipeline. Also, I'm not sure this instance  will build faster than a regular linux instance.

> the output should be shared with the two androidTest jobs

We can definitely try that, but iirc there are some limitations on the amount (size) of outputs between steps.

**Comment by JoseAlcerreca** [comment]
"the total size of all caches in a repository is limited to 10 GB."

This should be enough. We've been using caches in compose-samples and accompanist. Here's an example:

![image](https://github.com/android/nowinandroid/assets/609125/a9fd3709-29f0-4bec-8d13-785e8659ccf6)

https://github.com/android/compose-samples/actions/runs/6387359782/job/17335810161

JetChat seems to be storing 500Mb And Accompanist 700Mb:

https://github.com/google/accompanist/actions/runs/6767059523/job/18389092242

> I would personally advise against that. The build does not need any macos specific feature, and macos has a 10x multiplier on free tier pipeline. Also, I'm not sure this instance will build faster than a regular linux instance.

If we don't do this, the build needs to happen twice, in parallel, in macos, and once on linux.

**Comment by SimonMarquis** [comment]
(I was initially referring to [build outputs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) but these are String values only 🙈)

I'm not sure this caching mechanism does what you think.
In the [JetChat build you linked](https://github.com/android/compose-samples/actions/runs/6387359782), the cache is based on a key computed from Gradle build files (and .properties files).
This means the first job of the 1st workflow execution will populate the cache with whatever the job does, but prevents following update, like during edits to a PR (commits/rebases/merges), to update the cache if the key remains identical (GitHub Actions cache is [immutable](https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache)).
Therefore, this usage of GitHub Actions cache does not currently always represents the Gradle build cache state of the previous `build` step.

Maybe we could try to implement this solution on this project and see how it behaves. 👍

> If we don't do this, the build needs to happen twice, in parallel, in macos, and once on linux.

Can you elaborate on why this would be the case?
To me, most -if not all- of the Gradle build cache is independant of the OS it was generated on.
