### ISSUE TITLE
[Bug]: unit tests are executed twice per `Build.yaml` workflow execution

### ISSUE THREAD

**Issue by SimonMarquis** [android/nowinandroid#1018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

As discovered in https://github.com/android/nowinandroid/issues/1011#issuecomment-1792195181, [`Build.yaml`](https://github.com/android/nowinandroid/blob/f414cd482e67807b558653d3b9ef31f7fc4d1bd4/.github/workflows/Build.yaml) contains two instances of `gradlew testDemoDebug testProdDebug`:

- in the `build` job [~5min 50s](https://github.com/android/nowinandroid/actions/runs/6744267534/job/18333858408#check-step-10): https://github.com/android/nowinandroid/blob/f414cd482e67807b558653d3b9ef31f7fc4d1bd4/.github/workflows/Build.yaml#L49-L50

- in the `test` job [~14min 30s](https://github.com/android/nowinandroid/actions/runs/6744267534/job/18333858232#check-step-11):
https://github.com/android/nowinandroid/blob/f414cd482e67807b558653d3b9ef31f7fc4d1bd4/.github/workflows/Build.yaml#L107-L109

(the duration difference can be explain by the `build` job having already compiled most of the needed source code)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayaankhan98** [comment]
Can I proceed to fix this issue?

**Comment by SimonMarquis** [comment]
I think we should first find out what to do with #1011 and think about the bigger picture of job dependencies.

**Comment by ayaankhan98** [comment]
Okay, makes sense.

**Comment by JoseAlcerreca** [comment]
Fixed in #1019
