### ISSUE TITLE
[FR]: Add build workflow for app-nia-catalog

### ISSUE THREAD

**Issue by arriolac** [android/nowinandroid#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

The current `Build.yaml` workflow is specific to building and testing the `app` module, however, there are more than 1 apps in the project.

### Describe the solution

 An additional build/test workflow should be added to also build/test `app-nia-catalog`

### Additional context

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rocksnake** [comment]
I hope you can assign this issue to me, I will directly add the `build` workflow in `Build.yaml` to build the `app-nia-catalog` module.

However, there is a question about the `test` workflow of the `app-nia-catalog` module that needs to be answered, the `app-nia-catalog` module does not have the same functions as the app module and needs ui test. In the `app` module, the `Navigation` needs to do ui test. Do I need to add ui testing in the `app-nia-catalog`?

**Comment by arriolac** [comment]
@Rocksnake this issue is here for anyone to pick up, so feel free to take on :)

I think adding UI tests is out of scope for this issue, I was imaging this would purely be an improvement on the current workflow set up. Doing something like:
1. Create a reusable workflow similar to https://github.com/android/compose-samples/blob/main/.github/workflows/build-sample.yml
2. Update `Build.yaml` to use the reusable workflow
3. Create a new workflow that to build/test `app-nia-catalog`

**Comment by camina-apps** [comment]
I guess it make sense to wait for this PR https://github.com/android/nowinandroid/pull/130 to get merged

**Comment by arriolac** [comment]
@YuraLaguta great that you are helping out with this. You can have the workflow accept two parameters (like `uploadOutputs` and `uploadReports`) which can default to `true` but overridden by `app-nia-catalog` to set as `false` so the behavior of outputs of the workflows won't change.

**Comment by arriolac** [comment]
Thanks for clarifying. Yes, it makes sense to close this as the current workflow already accounts for both apps. I don't see much value in creating a separate workflow in that case.
