### ISSUE TITLE
[Bug]: Configuration cache disabled due to *OssLicensesTask 

### ISSUE THREAD

**Issue by JoseAlcerreca** [android/nowinandroid#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

```
% ./gradlew :app:assemble                
Calculating task graph as no configuration cache is available for tasks: :app:assemble
...
Configuration cache entry discarded because incompatible task was found: ':app:demoDebugOssLicensesTask'.
```

-----

Found https://github.com/google/play-services-plugins/issues/246 where the issue is confirmed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoseAlcerreca** [comment]
From [gradle docs](https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api/-task/not-compatible-with-configuration-cache.html): 

> 
The presence of incompatible tasks in the task graph will cause the configuration state to be discarded at the end of the build unless the global configuration-cache-problems option is set to warn, in which case the configuration state would still be cached in a best-effort manner as usual for the option.


I have no idea if `configuration-cache-problems` is safe to change. Thoughts?

**Comment by Goooler** [comment]
We can consider migrating to Licensee to fully support CC.
