### ISSUE TITLE
[Bug]: 🚨 `main` branch fails to run instrumented tests

### ISSUE THREAD

**Issue by SimonMarquis** [android/nowinandroid#1041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

https://github.com/android/nowinandroid/actions/runs/6893913811/job/18754556371#step:7:870

```
> Task :app:connectedDemoDebugAndroidTest
Starting 14 tests on test(AVD) - 8.0.0

com.google.samples.apps.nowinandroid.ui.NavigationTest > topLevelDestinations_showSettingsIcon[test(AVD) - 8.0.0] FAILED 
	java.lang.NoSuchMethodError: No static method layout$default(Landroidx/compose/ui/layout/MeasureScope;IILjava/util/Map;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)Landroidx/compose/ui/layout/MeasureResult; in class Landroidx/compose/ui/layout/MeasureScope; or its super classes (declaration of 'androidx.compose.ui.layout.MeasureScope' appears in /data/app/com.google.samples.apps.nowinandroid.demo.debug-bIGZ_x9GeXlhDoRTOeMxqg==/base.apk:classes10.dex)
	at androidx.compose.material3.adaptive.navigation.suite.NavigationSuiteScaffoldKt$NavigationSuiteScaffoldLayout$1$1.measure-3p2s80s(NavigationSuiteScaffold.kt:157)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
A solution could be to update the versions to the same stable version `1.1.2`, but this would mean we no longer necessarily follow the versioning of the BoM.

**Comment by SimonMarquis** [comment]
After digging a bit deeper, the issue initially comes from disabling the transitivity property of these two alpha dependencies:

https://github.com/android/nowinandroid/blob/f365e8b782892673436eb1043f022c7dad0f5927/app/build.gradle.kts#L119-L124

This tells Gradle to ignore transitive dependencies.
Which means that, the specific dependencies requested by these two artifacts will be ignored.
And this results in a runtime classpath error.

For example: if we decode the stacktrace, we can see that the compile classpath did not match the runtime classpath and therefore we have a runtime exception:

```
java.lang.NoSuchMethodError: No static method layout$default(MeasureScope, Int, Int, Map, Function1, Int, Object): MeasureResult in class Landroidx/compose/ui/layout/MeasureScope
```

Indeed, the dependency `androidx.compose.ui:ui-android` was previously coming directly from [`androidx.compose:compose-bom:2023.10.01`](https://mvnrepository.com/artifact/androidx.compose/compose-bom/2023.10.01) → [`androidx.compose.ui:ui-android:1.5.4`](https://mvnrepository.com/artifact/androidx.compose.ui/ui-android/1.5.4)
But at the same time the new alpha dependencies were requesting [`androidx.compose.material3:material3-adaptive:1.0.0-alpha01`](https://mvnrepository.com/artifact/androidx.compose.material3/material3-adaptive/1.0.0-alpha01) → [`androidx.compose.foundation:foundation:1.6.0-alpha08`](https://mvnrepository.com/artifact/androidx.compose.foundation/foundation/1.6.0-alpha08) → [`androidx.compose.ui:ui:1.6.0-alpha08`](https://mvnrepository.com/artifact/androidx.compose.ui/ui/1.6.0-alpha08)
And this is were the runtime collision happens.

At the moment, the two solutions that I can see are:
- embrace the alpha versions everywhere (not recommended)
- revert the PR that introduced these dependencies

**Comment by lihenggui** [comment]
No PRs have run successfully due to this bug now.

![image](https://github.com/android/nowinandroid/assets/5171312/5368aad4-f4a6-46e2-8afe-7c41e6574f5e)

**Comment by alexvanyo** [comment]
@mmoczkowski could you investigate after adding the `isTranstive = false` lines in #942?

**Comment by SimonMarquis** [comment]
Fixed by
- #1054
