### ISSUE TITLE
[FR]: add examples for flavor style overlay

### ISSUE THREAD

**Issue by Tornaco** [android/nowinandroid#1093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

When build app for different flavor, we have a while label project, and want to change ui styles for different flavor, that is easy on Android View by resource overlay.

But how to achive this on Compose? for example, we have a Text component in main src:

```kotlin
@Composable
fun MyText() {
    Text("Hello", color = Color.Red)
}
```

Want color to be Blue on A flovor, Yello on B flavor, so what's the best pattern?

### Describe the solution

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
This project already has two different selectable themes (`Default` vs `Android`) that you can switch between in the settings, in addition to a few other theme options (dark mode, dynamic color). That should be a good reference to see how theming can be customized based on more complicated logic or needs.
