### ISSUE TITLE
[Bug]: Your examples don't work??????

### ISSUE THREAD

**Issue by kaizer1** [android/nowinandroid#1135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

A bug happen
![Снимок экрана 2023-12-28 180500](https://github.com/android/nowinandroid/assets/5073933/3e0623cd-ef9c-4d71-8f25-64241fb5634e)
ed!
How can this....... be??? How - you are an official Google channel and the examples don’t work for you. You just download, launch and there’s a carload of errors???? HOW CAN THIS HAPPEN???? Nightmare

![Снимок экрана 2023-12-28 180500](https://github.com/android/nowinandroid/assets/5073933/8803a4ee-0c05-409a-b0f9-f60afac47e89)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kaizer1** [comment]
It's hard to control yourself. Some kind of super horror

**Comment by SimonMarquis** [comment]
@kaizer1 please be respectful here!

**Comment by kaizer1** [comment]
Ok. I'm downloads your repository and load in to Android studio - and see this error ( up ).

**Comment by tudang88** [comment]
Maybe you have already gone over the issue. The error seemed to be from the AndroidGradlePlugin version.
I've just tried with Android Studio Iguana and built the 'app' configuration. It works fine on the emulator.
