### ISSUE TITLE
[Bug]: enableEdgeToEdge() is causing ui issue

### ISSUE THREAD

**Issue by Pro-55** [android/nowinandroid#1205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

https://github.com/android/nowinandroid/assets/18625192/23d8f690-8dd6-4353-a53f-97823e428e33

https://github.com/android/nowinandroid/assets/18625192/1a794f2f-091e-4cd0-b1ea-c62851a9f8fd

After moving to enableEdgeToEdge() the Compose UI elements [Buttons] are being squished by the keyboard. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lihenggui** [comment]
Looks like this is not a bug in the nowinandroid project.

**Comment by Pro-55** [comment]
@lihenggui can you please point me in the right direction?

**Comment by lihenggui** [comment]
If you encounter any issues in your project, please visit StackOverflow to search existing questions or create a new one if it doesn't already exist. Use GitHub issues only for issues that pertain to the specific project.
