### ISSUE TITLE
GetSearchContentsCountUseCase should not exist

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#1283]
Callers should call the repository interface directly.

https://github.com/android/nowinandroid/blob/main/core/domain/src/main/kotlin/com/google/samples/apps/nowinandroid/core/domain/GetSearchContentsCountUseCase.kt

**Comment by sanao1006** [comment]
I will work on this issue.

**Comment by Jaehwa-Noh** [comment]
I wonder why we should remove that use case then migrate the business logic from repository?

When we decide to use optional domain layer, move the repository's business logic to domain layer. It makes sense to me.

I read this [documentation](https://developer.android.com/topic/architecture/domain-layer#threading).

<img width="738" alt="Threading" src="https://github.com/android/nowinandroid/assets/48680511/c605943b-c72a-4357-bab0-2ac136c869fe">


The reason of deleting use case is that so complicated to apply domain?
> Typically, complex computations happen in the data layer to encourage reusability or caching. For example, a resource-intensive operation on a big list is better placed in the data layer than in the domain layer if the result needs to be cached to reuse it on multiple screens of the app.


And ```complex computations``` is so abstract word, then I am hard to decide and determine the baseline when I choose whether use domain layer or not.

In this 'Now in Android', is this GetSearchContentsCountUseCase, and getSearchContentsCount in DefaultSearchContentRepository business logic complex to use in domain?

**Comment by yongsuk44** [comment]
Following the same reasoning, what do you think about eliminating `GetRecentSearchQueriesUseCase` and instead allowing `SearchViewModel` to directly interact with the repository interface? This could simplify the architecture.

@dturner
