### ISSUE TITLE
[Bug]: `ForYouScreen` and `InterestsScreen` TopAppBar background color

### ISSUE THREAD

**Issue by SimonMarquis** [android/nowinandroid#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

`ForYouScreen` and `InterestsScreen` are not using the same background color:

| `ForYouScreen` | `InterestsScreen` | Diff |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/1921278/168166107-0d531547-75f5-472c-a842-cd6a45f0df08.png) | ![image](https://user-images.githubusercontent.com/1921278/168166150-e00f9424-2961-4923-9122-b24d9ed9a337.png) | ![0atetime%-diff](https://user-images.githubusercontent.com/1921278/168166669-9ddf18d2-9989-475a-8bf9-dbcc44d510bc.png) |

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
I believe this is resolved with the current version of the app, closing!
