### ISSUE TITLE
[Bug]:  Failed Build

### ISSUE THREAD

**Issue by asiimwedismas** [android/nowinandroid#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Can't seem to build this with following output

### Relevant logcat output

```shell
Execution failed for task ':build-logic:convention:compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':build-logic:convention:compileKotlin'
   > Could not resolve all files for configuration ':build-logic:convention:kotlinCompilerPluginClasspathMain'.
      > Could not find org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.5.31.
        Required by:
            project :build-logic:convention
      > Could not find org.jetbrains.kotlin:kotlin-sam-with-receiver:1.5.31.
        Required by:
            project :build-logic:convention

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
This looks very similar to #37 .

Could you include more information about when this error happened, and how you loaded the project?

Did you encounter this error when building from the command line? (`./gradlew check` or similar)
Did you load the project via Android Studio, and if so, which version? Did this error happen during sync, or attempting to run the app, or some other time?

**Comment by asiimwedismas** [comment]
So below are the details of my system and android versions that have both failed to build the project. Same results for both command line and hammer build methods in both android studio versions that I have listed below.

macOS 12.4 Monterey (21F79)

Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.jetbrains.CyanTheme (1.3), com.jetbrains.darkPurpleTheme (1.3), Key Promoter X (2021.3), wu.seal.tool.jsontokotlin (3.7.4), org.jetbrains.kotlin (212-1.7.0-release-281-AS5457.46), izhangzhihao.rainbow.brackets (6.24)


Android Studio Electric Eel | 2022.1.1 Canary 2
Build #AI-213.7172.25.2211.8571212, built on May 11, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

**Comment by alexvanyo** [comment]
@asiimwedismas do you know if you had Offline Mode enabled before wiping `~/.gradle`?

**Comment by asiimwedismas** [comment]
> @asiimwedismas do you know if you had Offline Mode enabled before wiping `~/.gradle`?

always online..

**Comment by asiimwedismas** [comment]
> Or a custom initialization script in `init.d`. No problem if you don't remember, just trying to track down the root cause!

I think I might have had that considering I had downloaded and set up the google maven offline repository

**Comment by alexvanyo** [comment]
> google maven offline repository

Ah, that makes sense! That matches the reason we saw the issue as well. Technically you only needed to delete that, and not wipe all of `.gradle`, sorry for the very slow build time that occurred after doing that 😄

**Comment by asiimwedismas** [comment]
a cool 17m of build time...taught me to be patient...🫡 thanks for the solution though, I was afraid I was going to have to switch to my PC for this one project...👍🏽

**Comment by YUSMLE** [comment]
You also can perform following commands to refresh the dependencies instead of deleting Gradle cache: 

`# Clear the build cache of current project
.\gradlew cleanBuildCache

# Refresh the dependencies instead of deleting Gradle cache (local or global .gradle folder)
.\gradlew build --refresh-dependencies`
