### ISSUE TITLE
[Bug]: why WithPartialCompilationAndDisabledBaselineProfile is the best result in StartupBenchmark

### ISSUE THREAD

**Issue by hxu-wish** [android/nowinandroid#1345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

In startupbenchmark file, we have four ways to test the startup performance

1. WithoutPreCompilation
2. PrecompiledWithBaselineProfile
3. WithPartialCompilationAndDisabledBaselineProfile
4. FullyPrecompiled

Then I run and found out that 3 is the best way for performance.

Why it happen. It did not use baseline profile at all. Is there anything wrong?

### Relevant logcat output

StartupBenchmark_startupWithoutPreCompilation timeToInitialDisplayMs   min 1,279.5,   median 1,312.9,   max 1,459.9 Traces: Iteration 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
StartupBenchmark_startupPrecompiledWithBaselineProfile
timeToInitialDisplayMs   min       862.2,   median       889.2,   max 1,103,080.4 improve 34%
Traces: Iteration 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
StartupBenchmark_startupWithPartialCompilationAndDisabledBaselineProfile
timeToInitialDisplayMs   min 735.0,   median 757.1,   max 786.2 improve 42%
Traces: Iteration 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
StartupBenchmark_startupFullyPrecompiled
timeToInitialDisplayMs   min   855.4,   median   886.7,   max 1,074.9 improve 32%
Traces: Iteration 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jaehwa-Noh** [comment]
I think this should be in ```Discussions```.

**Comment by hxu-wish** [comment]
Thanks, new a new discussion here https://github.com/android/nowinandroid/discussions/1348
Let me close this issue.
