### ISSUE TITLE
[FR]: Minimize Unnecessary Recompositions

### ISSUE THREAD

**Issue by KDW03** [android/nowinandroid#1353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

In current implementation of NiaApp, we've observed an issue where unrelated state changes, such as modifications to showSettingsDialog, trigger unnecessary recompositions across the entire app, including within NiaNavHost and its child screens

Upon investigation, we identified that lambda expressions, such as onTopicClick, are being recreated with each recomposition cycle. Compose treats these newly instantiated lambda expressions as different from their predecessors, thus triggering recompositions even when there are no pertinent state changes.

![image](https://github.com/android/nowinandroid/assets/109224863/8ab509ad-5b9d-4c75-9888-3b3c28535ea5)

this behavior will persist until the Jetpack Compose Compiler is updated to version 1.7, which is expected to introduce an enhanced 'Strong skipping' mode for more efficient recomposition skipping. In the meantime, developers are advised to manage lambda instances manually using remember to mitigate unnecessary recompositions.

This is particularly evident in screens like ForYouScreen, where the onTopicClick lambda is passed down and utilized. Despite showSettingsDialog having no direct relation to these screens, they undergo recomposition, leading to performance inefficiencies.

### Describe the solution

I propose to mitigate this issue by employing the `remember` construct to cache navigation-related lambda expressions within `NiaNavHost`. This approach will ensure that lambdas are only recreated when genuinely necessary, such as when the `NavController` instance changes

### change
![image](https://github.com/android/nowinandroid/assets/109224863/72cfa03c-2af5-460f-a0e6-126bdd6917ac)

### before
![image](https://github.com/android/nowinandroid/assets/109224863/a3cb7e3a-496d-4f71-b7df-25db9b2d9cb0)

### after
![image](https://github.com/android/nowinandroid/assets/109224863/583fba61-9068-4c79-b5a1-625313f1cc2e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bentrengrove** [comment]
This was a great investigation and your conclusion is correct! We will be enabling strong skipping mode in this project very soon so it isn't worth implementing the fix to manually remember lambdas. It would actually introduce a small amount of tech debt as the `remember` would become redundant once strong skipping is enabled.

I'll close this issue out but thank you for the report.
