### ISSUE TITLE
[Bug]: enableEdgeToEdge() doesn't change the navigation bar color when the app is in the dark mode and the system is not in Android 14

### ISSUE THREAD

**Issue by Omico** [android/nowinandroid#1358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

When the system isn't in the dark theme
![image](https://github.com/android/nowinandroid/assets/14316223/c5963e4a-60d8-47ee-981e-56a49290c6dd)

When the system is in the dark theme
![image](https://github.com/android/nowinandroid/assets/14316223/53d5683a-9a44-4f34-875b-1423381aca28)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
It looks like this is the system taskbar, which always matches the system theme setting and isn't controllable by apps.

There's nothing that Now in Android or `enableEdgeToEdge` can do here.
