### ISSUE TITLE
Wrong Search History State

### ISSUE THREAD

**Issue by Sagar0-0** [android/nowinandroid#1379]
Steps:
1. Go to Search Screen
2. Open your keyboard
3. Click on Search IME action in your keyboard.
4. See the unwanted "close" button appeared for Recent searched even when there is no search history
https://github.com/android/nowinandroid/assets/85388413/2832a42b-1a48-4c45-8712-187964cf4dac

Fix:
1. Logic for showing the "close" icon button should be dependent on the Recent search list
2. If the size of list is greater than 0 then we can show the button.
3. If the size is 0 then hide the button
4. We can observe the button visibility state on the list size.

This issue is tested in the latest dev build and in ANDROID 14

**Comment by Jaehwa-Noh** [comment]
Hi,
Kindly check these issue and pull request.
- Issue #1222 
- Pull request #1223

**Comment by Sagar0-0** [comment]
It looks like the same issue. Closing this one as Duplicate.
