### ISSUE TITLE
Why is this project blank when I run it?

### ISSUE THREAD

**Issue by DULLONEX** [android/nowinandroid#1418]
please help me.I unskilled about `nowinandroid`
<img width="333" alt="image" src="https://github.com/android/nowinandroid/assets/63269574/e5ae7cb2-20f6-4ae1-b60c-42391f3f2d84">

**Comment by Jaehwa-Noh** [comment]
Could you tell me more details?
What does your build variants use when build?

**Comment by DULLONEX** [comment]
> Could you tell me more details? What does your build variants use when build?

I not know I just download this project, after by android-Studio's default build to run. 
the git'branch is main.
<img width="349" alt="image" src="https://github.com/android/nowinandroid/assets/63269574/bea56410-d5bc-480b-a43e-d49969dc18d6">
this is my project catalogue.

**Comment by Jaehwa-Noh** [comment]
This project is using room database for demo build project.
I'm not sure, but I'm thinking that room database part went something wrong.
However, I don't know what's going on your device and Build, so that It is me hard to know what happened.

**Comment by DULLONEX** [comment]
> 该项目使用房间数据库进行演示构建项目。 我不确定，但我认为房间数据库部分出了问题。 然而，我不知道你的设备和Build上发生了什么，所以我很难知道发生了什么。
> 
> 另一个期望是，您的设备看起来没有连接到互联网。 请检查互联网连接。

wooooow! yout right.  This is my mistake. I am so sorry because I do not examine log info.
