### ISSUE TITLE
[Bug]: Added New screenshot have failed in CI local test

### ISSUE THREAD

**Issue by Jaehwa-Noh** [android/nowinandroid#1421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Added New screenshot have failed in CI local test #1296 

I had added new screenshot for snackbar test on my Mac. See below.
https://github.com/android/nowinandroid/pull/1296/commits/afe53f90966cd35a4f7233d7a8a4aa7ea84ff45f

But, the result was failed because of these differences.
Here is the output from [CI](https://github.com/android/nowinandroid/actions/runs/9017850460/job/24777165436#step:17:708).

![snackbar_expanded_expanded_compare](https://github.com/android/nowinandroid/assets/48680511/8483263e-104b-49f1-a909-2c65f3c049ae)

![snackbar_medium_medium_compare](https://github.com/android/nowinandroid/assets/48680511/bd9b2e45-2832-4fd7-8d36-db2535460a6b)

What I'm missing? or What should I do?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
@Jaehwa-Noh you can let the CI generate them for you. Simply open a PR in your fork, and the CI will automatically commit these files during the build.

**Comment by Jaehwa-Noh** [comment]
@SimonMarquis Aha, the screenshot tests followed Single-Source-Of-Truth. Good.
I'm totally understand. Thank you SimonMarquis!
