### ISSUE TITLE
[FR]: Upgrade to AGP 8.4

### ISSUE THREAD

**Issue by jvandort** [android/nowinandroid#1433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Gradle uses NIA as a sample project for its performance tests. Since NIA is not compatible with AGP 8.4, we cannot update Gradle's tests to perform validations against AGP 8.4. These include both our smoke tests and performance benchmarks, as they both test against the same AGP versions.

### Describe the solution

Update NIA to build with AGP 8.4

### Additional context

This blocks the following Gradle PR: https://github.com/gradle/gradle/pull/29102

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jvandort** [comment]
@alexvanyo You upgraded to 8.3 [last time](https://github.com/android/nowinandroid/pull/1140). How difficult do you think this upgrade will be?

**Comment by SimonMarquis** [comment]
@dependabot should have taken care of it like in this PR:
- https://github.com/android/nowinandroid/pull/1114

Unfortunately, I think the project accumulated too many open PRs:
https://github.com/android/nowinandroid/blob/7f2ce57c67c68aa921de9231525a4a47ef431fe8/.github/dependabot.yml#L21

**Comment by jvandort** [comment]
Thank you for the quick turn-around time!
