### ISSUE TITLE
Compose Preview Screenshot Testing 

### ISSUE THREAD

**Issue by JackEblan** [android/nowinandroid#1462]
What do you think about [Compose Preview Screenshot Testing ](https://developer.android.com/studio/preview/compose-screenshot-testing)

You guys really did a great job making screenshot testing simplier and I can finally use this on my Windows 😂 but I'm gonna wait for your signal if you guys are going to migrate to **Compose Preview Screenshot Testing**

**Comment by Jaehwa-Noh** [comment]
I saw it in Google I/O 2024.
I assumed that the roborazzi screenshot will be replaced to Compose Preview Screenshot Testing, maybe.

**Comment by ParkJong-Hun** [comment]
There is still more available from Roborazzi, so I think it would be okay to use both at the same time.

**Comment by dturner** [comment]
Please don't post questions here. This is for issues associated with the Now in Android app project.
