### ISSUE TITLE
[Bug]: Cross linking navigation doesn't work correctly

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#1463]
Steps to repro:

- On the ForYou screen, tap on any topic chip within a news resource card. The topic detail screen opens for that topic. It is in the Interests nav graph. 
- Tap on ForYou in the nav bar/rail

Expected result: 

- The ForYou screen is shown again

Actual result: 

- Nothing happens

**Comment by jeonhei** [comment]
I have the same problem.This problem is caused by the Navigation library and I've never been able to figure it out.

**Comment by jeonhei** [comment]
It worked!Thank a lot!
