### ISSUE TITLE
[Bug]: Build Broken

### ISSUE THREAD

**Issue by Jaehwa-Noh** [android/nowinandroid#1544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Removed dependency.

<img width="418" alt="image" src="https://github.com/user-attachments/assets/6e254147-ef37-45da-a211-910574568b5f">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
@Jaehwa-Noh the issue is more broad than that. Unit tests from non-Android modules are not executed. I'll create a dedicated issue for that.

**Comment by Jaehwa-Noh** [comment]
Fixed #1667
