### ISSUE TITLE
[FR]: In the file ScrollbarExt.kt there is room for reducing the logic and code repeating in order to improve the reusability and maintainability

### ISSUE THREAD

**Issue by rodrigodiasferreira** [android/nowinandroid#1549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

In the file ScrollbarExt.kt file there is room for reducing the logic and code repeating in order to improve the reusability and maintainability.
Moreover, this improvement will make it better for developers who use the nia sample to study, and learn ways to use Kotlin to increase resusability.
The `scrollbarState` extension function for the LazyListState, LazyGridState, LazyStaggeredGridState have a lot of common logic that could be unified.

### Describe the solution

My suggestion is to unify into a more generic extension function:
`<LazyState : ScrollableState, LazyStateItem> LazyState.genericScrollbarState`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigodiasferreira** [comment]
Hi there, 
I would like to contribute to Now In Android sample.
I've already developed such improvement, but I'm not able to upload it.

I've already signed the Google Individual CLA.
I can upload new PRs to my repositories, but for Now in Android it says to check if I have the correct access rights.

I am trying to upload the branch where I developed the improvement: `scrollbarext-improvement`
`git push --set-upstream origin scrollbarext-improvement`

This is the error I got:
```
ERROR: Permission to android/nowinandroid.git denied to rodrigodiasferreira.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
```

Anyone can help me to check if I am doing something wrong?

Thanks.

**Comment by Jaehwa-Noh** [comment]
Follow these steps.
1. Fork this repository into your repository.
2. Open 'your forked repository' on the Android Studio.
3. Edit your code, and push to your forked repository.
4. Make PR at this origin repository.

**Comment by rodrigodiasferreira** [comment]
Hi @Jaehwa-Noh, thanks a lot for the tips.
I've just upload the PR: https://github.com/android/nowinandroid/pull/1550, I mentioned this issue on the PR, but maybe it should be linked through the development right side bar on this issue, but I don't have permission to do that.
I also do not have permission to self assign this issue to me.

It's my first contribution, so if there is any adjustment, or anything that I should improve, please let me know, I will do my best to conform to your standards.
Thanks!

**Comment by rodrigodiasferreira** [comment]
I am closing this issue, as commented by @tunjid on PR: https://github.com/android/nowinandroid/pull/1550, the split of the functions and logic duplication was done on purpose, in order to improve readability.
