### ISSUE TITLE
[Bug]: Not able to return to "For You" screen from Topic screen

### ISSUE THREAD

**Issue by devwindsw** [android/nowinandroid#1597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

[Repro Steps]
1. Click a topic in "For You" screen and verify that the topic screen is launched
2. Click "Back" button in the top bar
3. Click "For You" tab in the bottom bar

[Expected Result]
We can navigate to "For You".

[Actual Result]
We're not able to navigate to "For You" until restart the app

[Frequency] 100%

[Screen_recording_20240906_023148.webm](https://github.com/user-attachments/assets/26c15304-12e4-477e-8721-ffff63942185)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anhtuannd** [comment]
Maybe it's duplication of https://github.com/android/nowinandroid/issues/1463 and https://github.com/android/nowinandroid/issues/1465

**Comment by devwindsw** [comment]
> Maybe it's duplication of #1463 and #1465

The same issue happens even with the PR https://github.com/android/nowinandroid/pull/1470/commits/4c725bfe5dd8203479518e713bb495a8f28218ad

**Comment by anhtuannd** [comment]
I rebased my commit to latest. You can check again, apparently I don't see this happen.

**Comment by devwindsw** [comment]
> I rebased my commit to latest. You can check again, apparently I don't see this happen.

In "with_fix", we can find "LoadingWheel" is displayed and disappears shortly but not in "without_fix".

[without_fix.webm](https://github.com/user-attachments/assets/07000bfa-605a-4559-b3e2-693bf5436c38)
[with_fix.webm](https://github.com/user-attachments/assets/6bd0636b-37e1-443a-ab02-c7b6d015ddb8)
