### ISSUE TITLE
Type mismatch: inferred type is Short.Companion but SnackbarDuration was expected

### ISSUE THREAD

**Issue by padrecedano** [android/nowinandroid#1624]
https://github.com/android/nowinandroid/blob/a83c8731419a9297fd79c27396d7cee9e697b21a/app/src/main/kotlin/com/google/samples/apps/nowinandroid/ui/NiaApp.kt#L241

I'm having the error:

> Type mismatch: inferred type is Short.Companion but SnackbarDuration was expected

## `NiaApp`

        import androidx.compose.material3.SnackbarResult.ActionPerformed

        /* Some code */

                   NiaNavHost(
                        appState = appState,
                        onShowSnackbar = { message, action ->
                            snackbarHostState.showSnackbar(
                                message = message,
                                actionLabel = action,
                                duration = Short,
                            ) == ActionPerformed
                        },
                    )

##  `NiaNavHost`

```
fun NiaNavHost(
    appState: NiaAppState,
    onShowSnackbar: suspend (String, String?) -> Boolean,
    modifier: Modifier = Modifier,
) {
```

Is this a bug in the code or am I missing some implementation?

**Comment by Jaehwa-Noh** [comment]
It seems you import wrong `Short`, you need to import `SnackbarDuration.Short`

**Comment by padrecedano** [comment]
@Jaehwa-Noh You're right. That was the problem. Thank you.
