### ISSUE TITLE
[Comments]: Can we have some accurate comments for each file of source code to help understanding?

### ISSUE THREAD

**Issue by polarove** [android/nowinandroid#1641]
For those beginners to this project: 

This project is growing larger as days gone, and we have people from different cultures contributing on it, leading me to a situation where `naming conventions` / `complex project structure` / `giant project dependencies` are not efficient for understanding.

**Let's first talk about the naming conventions**
1. The `NiaApplication`, the `Nia`, is that a cat meow?

2. Names begin with `Offline` ( [`OfflineFirstTopicsRepository`](https://github.com/android/nowinandroid/blob/573cf2d1b8bc505fb9183822f6484991140ff990/core/data/src/main/kotlin/com/google/samples/apps/nowinandroid/core/data/repository/OfflineFirstTopicsRepository.kt#L38) ) indicate `LocalDevice`:

    Such classess will fetch some data from the internet in [some cases](https://github.com/android/nowinandroid/blob/573cf2d1b8bc505fb9183822f6484991140ff990/core/data/src/main/kotlin/com/google/samples/apps/nowinandroid/core/data/repository/OfflineFirstTopicsRepository.kt#L53), it's not consist with its name `Offline****`. 

    It should only execute functions from `xxxDao` to perform local data  ( which might be outdated in user's device ) operation accroding to its name, ideally. 

    otherwise just don't name it as `Offline***`, because it uses network indeed.

4. Names end with [`Repository`](https://github.com/android/nowinandroid/blob/573cf2d1b8bc505fb9183822f6484991140ff990/core/data/src/main/kotlin/com/google/samples/apps/nowinandroid/core/data/repository/OfflineFirstTopicsRepository.kt#L38) are pretty straight forward, might be holding datasource from both local device and network requests

5. Names like `Network****Resource****` ( `NetworkNewsResourceExpanded` ) indicate  `used to receive data from network requests`, why don't we name it like `NewsVo`, `Vo` means `View Object`, and `ViewModel` classes (`NewsViewModel`) can have multiple `Vo`s:
  ```kotlin
   class NewsViewModel : ViewModel() {
           val NewsList: List<NewsVo> = emptyList()
           val OutdatedNewsList: List<NewsVo> = emptyList()
   }
   
   data class NewsVo (
            val title: String,
            val content: String
   )
   ```

6. Names end with `DataSource` indicate `a class that has some method sused to fetch data from the internet`

7. Names end with `Dao` indicate `a class that has some SQL annotated methods used to operate data in sqlite (might be outdated)  on local device`.

8. And more.....

**The complex project structure is really refusing me to understand a data flow**

It's seperated into different modules inside different files, with interfaces hiding thier actual multiple implementations behind. I often lost in `ctrl + right click` in android studio's reference prompt, hard to say that this is a better parttern to be maintained.

**Giant project dependencies**

There are to many dependencies that need you to review

**Comment by lihenggui** [comment]
> The NiaApplication, the Nia, is that a cat meow?

Nia represents for NowInAndroid

> Names begin with Offline ( [OfflineFirstTopicsRepository](https://github.com/android/nowinandroid/blob/573cf2d1b8bc505fb9183822f6484991140ff990/core/data/src/main/kotlin/com/google/samples/apps/nowinandroid/core/data/repository/OfflineFirstTopicsRepository.kt#L38) ) indicate LocalDevice:

It is not just `Offline`; it is actually `OfflineFirst`.You can refer the Android documentation for more information on this concept: https://developer.android.com/topic/architecture/data-layer/offline-first.

> why don't we name it like NewsVo, Vo means View Object, and ViewModel classes (NewsViewModel) can have multiple Vos 

You can use your preferred naming conventions in your project. People have varying preferences for conventions.  I believe most people may not understand what VO stands for and might ask the same question you did.

> The complex project structure is really refusing me to understand a data flow
Please read these two documents, it will help you understand why modularization is important and NIA is a showcase for this concept.
https://github.com/android/nowinandroid/blob/main/docs/ModularizationLearningJourney.md
https://github.com/android/nowinandroid/blob/main/docs/ModularizationLearningJourney.md

You can view https://github.com/android/compose-samples for simpler samples.


> Giant project dependencies
You can check out the quickstart guide provided by Google: https://developer.android.com/develop/ui/compose/setup. It's a great starting point for beginners.
Now in Android is a fully functional Android app built entirely with Kotlin and Jetpack Compose. It follows Android design and development best practices and is intended to be a useful reference for developers. As a running app, it's intended to help developers keep up-to-date with the world of Android development by providing regular news updates.

IMO it should be moved to discussion. It is not an issue though. 

More discussion about architecture: 
https://github.com/android/nowinandroid/discussions/1225
https://github.com/android/nowinandroid/discussions/574
https://github.com/android/nowinandroid/discussions/619

**Comment by dturner** [comment]
Thank you @lihenggui for answering these questions.
