### ISSUE TITLE
[Bug]: Screen is not retained after process death

### ISSUE THREAD

**Issue by gyorgygabor** [android/nowinandroid#1664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Steps to reproduce:
1. Open the app
2. Go to Interests -> Accessibility(just an example)
3. Put the app in the background
4. Trigger a process death
5. Reopen the app

Result: The For You screen is opened, instead of the last opened screen(Interests -> Accessibility)

Tested on Samsung S20, demoDebug build.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vivek-2004** [comment]
Seems that this is not a bug, rather a normal behaviour of the app.

**Comment by alexvanyo** [comment]
I can't reproduce this with the latest `main` code. Please re-open if you can still reproduce.

**Comment by vvb2060** [comment]
@alexvanyo 
open the app
scroll the list
switch to other app
exec `am kill com.google.samples.apps.nowinandroid` to simulate the system-initiated process death
come back to this app
the scroll position of list is lost

**Comment by vvb2060** [comment]
A user also expects your activity's UI state to remain the same if they temporarily switch to a different app and then come back to your app later. For example, the user performs a search in your search activity and then presses the home button or answers a phone call - when they return to the search activity they expect to find the search keyword and results still there, exactly as before.

In this scenario, your app is placed in the background the system does its best to keep your app process in memory. However, the system may destroy the application process while the user is away interacting with other apps. In such a case, the activity instance is destroyed, along with any state stored in it. When the user relaunches the app, the activity is unexpectedly in a clean state. To learn more about process death, see [Processes and Application Lifecycle](https://developer.android.com/guide/components/activities/process-lifecycle).

**Comment by vvb2060** [comment]
Interesting, only the scroll position of for you tab is not saved, the scroll position of other lists is stored normally. I think this is a bug.
