### ISSUE TITLE
[Bug]: configuration-cache disabled by mistake?

### ISSUE THREAD

**Issue by ErikHellman** [android/nowinandroid#1668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Not exactly a bug, but I noticed that `org.gradle.configuration-cache` is set to `false` for the project in `gradle.properties` and I'm curious if this is a mistake. I see that it was introduced in this PR: https://github.com/android/nowinandroid/pull/1173

Since this is a show case app where best-practices should be apply, maybe this should be enabled?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
@keyboardsurfer (owner of the original PR https://github.com/android/nowinandroid/pull/1173) to confirm whether this was disabled by mistake.

**Comment by keyboardsurfer** [comment]
I have been experimenting with configuration caching. Let's re-enable it for now.
