### ISSUE TITLE
[FR]: Add androidx.lint:lint-gradle to lint against convention plugin 

### ISSUE THREAD

**Issue by alexvanyo** [android/nowinandroid#1676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Writing conventions plugins have many easy ways to break caching or laziness, which https://developer.android.com/jetpack/androidx/releases/lint helps guard against.

### Describe the solution

Integrate https://developer.android.com/jetpack/androidx/releases/lint to lint the `build-logic` convention plugins.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
If feel like this should not only be added to the `:build-logic` module, but to all Gradle modules.
