### ISSUE TITLE
[FR]: Can theme switching enable dynamic replacement of icons in the APP?

### ISSUE THREAD

**Issue by whyNotBanMagna** [android/nowinandroid#1687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I want to know how ComposeUI can implement theme switching and dynamically change the small icons in the application.

### Describe the solution

I don't know how to solve it, so I would like to ask if you have any good solutions in ComposeUI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
This isn't the place for questions I'm afraid. Please try stackoverflow.
