### ISSUE TITLE
[Documentation]: How to Build a complex Android app in the google company?

### ISSUE THREAD

**Issue by anlexN** [android/nowinandroid#1696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Page URL (type "NEW" for a new page suggestion)

https://github.com/android/nowinandroid/

### What's the documentation problem or suggestion?

[This is about windows' practice](https://learn.microsoft.com/en-us/windows/uwp/get-started/plan-your-app)

I have reviewed `nowinandroid` source code step by step. But I still can not understand how you design this app. I think your theory are fragmented. one theory is one fragment.

I want to know you google team how to design a app. please reply me. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
Do not ask questions that aren't related to this project here. There are plenty of resources available to help you get started with Android development. I would start with https://developer.android.com/courses.
