### ISSUE TITLE
[Bug]: Unresponsive `Interests` navigation button

### ISSUE THREAD

**Issue by SimonMarquis** [android/nowinandroid#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

When navigating to either a `AuthorDestination` or `TopicDestination`, the `NavigationBar`'s `NavigationBarItem` corresponding to `InterestsDestination` becomes unselected and clicking on it does nothing.

It seems that the `NavDestination`'s hierarchy is not properly configured.

https://user-images.githubusercontent.com/1921278/168175101-d68877b5-3fa5-4f38-803e-5269c381d381.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kasem-sm** [comment]
Can I raise a PR for this Issue?

**Comment by JolandaVerhoef** [comment]
Our designs specify that the bottom bar should always show, also when navigating to a topic or author. Can you try to fix the bug of keeping the right tab selected instead?

**Comment by kasem-sm** [comment]
@JolandaVerhoef I got it, I would edit the PR with the changes as suggested by you. Thank You!

**Comment by SaeedNoshadi89** [comment]
> Our designs specify that the bottom bar should always show, also when navigating to a topic or author. Can you try to fix the bug of keeping the right tab selected instead?

@JolandaVerhoef I want to work on this issue. should I create a new issue about that or you can reopen this issue?

**Comment by simona-anomis** [comment]
This was fixed in the latest set of changes, thanks for raising it!
