### ISSUE TITLE
[Bug]: CI test failed on Build / androidTest (30) 

### ISSUE THREAD

**Issue by Jaehwa-Noh** [android/nowinandroid#1705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Since #1699 had been merged, Build / androidTest (30) was failed. 
See the actions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
I'm not sure this is really related to this specific PR, because the errors mentions an error while trying to stop the emulator:

- https://github.com/ReactiveCircus/android-emulator-runner/issues/385


```
Terminate Emulator
  /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 emu kill
  OK: killing emulator, bye bye
  OK
INFO    | Wait for emulator (pid 2266) 20 seconds to shutdown gracefully before kill;you can set environment variable ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL(in seconds) to change the default value (20 seconds)

INFO    | Snapshots have been disabled by the user, save request is ignored.
ERROR   | stop: Not implemented
WARNING | Emulator client has not yet been configured.. Call configure me first!
```

**Comment by dturner** [comment]
Switched to emulator API 34. Hopefully this will resolve.
