### ISSUE TITLE
[Bug]: Main is broken

### ISSUE THREAD

**Issue by Jaehwa-Noh** [android/nowinandroid#1717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Current main branch is broken.
Check this github action.
https://github.com/android/nowinandroid/actions/runs/12234913943

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blue928sky** [comment]
Perhaps it is related to this issue.
https://github.com/firebase/firebase-android-sdk/issues/5997

**Comment by dturner** [comment]
Some PRs were merged that shouldn't have been. Build should be fixed now. Thanks for reporting this.
