### ISSUE TITLE
If the Build workflow fails, the SARIF upload also fails

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#1759]
If the Build workflow fails, no SARIF files are created and the "Upload lint reports (SARIF)" step also fails with: 

Error: No SARIF files found to upload in "./".

For example: https://github.com/android/nowinandroid/actions/runs/12379945378/job/34555220383?pr=1757. 

When opening the failed workflow, the default view is to show the last error. This makes things confusing because it's not the SARIF upload step that is the root cause of failure. 

@SimonMarquis any chance you could take a look and change the SARIF upload step so that it only attempts the upload if the SARIF files have been created?

**Comment by SimonMarquis** [comment]
A PR has been created to fix this issue.
It now only runs when the workflow is not canceled and at least one sarif file is found.
