### ISSUE TITLE
[FR]: Provide a graph of the module structure

### ISSUE THREAD

**Issue by StylianosGakis** [android/nowinandroid#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Especially for someone newer to multi-modular apps, looking at all the modules on the top level of the project can be daunting.

### Describe the solution

It would be awesome if an always up-to-date graph of how the modules depend on each other could be shown in the README of this repository.

### Additional context

I was recently reading the article "Jetpack Compose — Before and after" from [Chris Banes](https://medium.com/androiddevelopers/jetpack-compose-before-and-after-8b43ba0b7d4f) and in that post, the section "The app" with the figure named "Graph of Tivi’s module structure. Generated using [Jake Wharton](https://twitter.com/JakeWharton)’s handy [Gradle task](https://github.com/JakeWharton/SdkSearch/blob/master/gradle/projectDependencyGraph.gradle)" is exactly what I am talking about. I hope you can refer to it for some inspiration.
This would give a visualization of how everything is structured in an instant without having to look at the gradle files of all modules.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
@mmoczkowski is this complete?
