### ISSUE TITLE
[Internal clean up]: NavController in NiaApp doesn't follow the SSOT principles

### ISSUE THREAD

**Issue by manuelvicnt** [android/nowinandroid#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

The `navController` state declared in `NiaApp` doesn't follow the single source of truth principles. There are 3 places where this state can be mutated: `NiaApp`, `NiaTopLevelNavigation`, and `NiaNavHost`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
@manuelvicnt was this fixed with #186 ?

**Comment by manuelvicnt** [comment]
Yes! It was. We'll probably need to make further changes but it's good as it is now! Thanks
