### ISSUE TITLE
[Bug]: mention core-designsystem module in the modularization journey docs

### ISSUE THREAD

**Issue by StylianosGakis** [android/nowinandroid#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Not necessarily a bug, but a docs "bug" if one can call it that.
The module core-designsystem is not mentioned in the modularization learning journey at the section where there is a list which should mention all of the app's design system.
On top of that it says that stuff like icons etc are part of core-ui but they are now moved into core-designsystem.
It would be a good idea to update that documentation page and be explicit about what you believe should live in a core-designsystem module and what in a core-ui one because as it stands it is a bit up to interpretation and can easily be confusing as I see it.

ps. I think it'd be a good idea to introduce a new Issue template for documentation problems because this does not fit a feature request nor a bug report imo.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
Thanks for the feedback. We'll update the learning journey. 

Also thanks for the suggestion to create a docs issue template. Created https://github.com/android/nowinandroid/pull/201 to add this.
