### ISSUE TITLE
[Observation]: Release yml is incorrect in github actions, looks like copied from Jetpack samples 

### ISSUE THREAD

**Issue by khalid64927** [android/nowinandroid#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

This is not a bug as of now but just some observation (review comment) on file in master branch

.github/workflows/Release.yml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
Thanks for noticing! This should be fixed with #130
