### ISSUE TITLE
[Bug]: forYou's NewsFeed has no space at the bottom of the last item

### ISSUE THREAD

**Issue by tenSunFree** [android/nowinandroid#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

The NewsFeed of forYou does not leave spaces at the bottom of the last item.
![01](https://user-images.githubusercontent.com/23090085/182022350-cb910fd2-58ff-4002-8659-3e8a92164db1.png)

if spaces are added, the user's visual experience may be better.
![02](https://user-images.githubusercontent.com/23090085/182022385-3a635398-2f32-4e01-a1b4-22fe5e9b4150.png)

Consider simply adding contentPadding = PaddingValues(bottom = 16.dp).
![03](https://user-images.githubusercontent.com/23090085/182022406-dd9188b3-7040-4334-89f7-30b7f3c58d13.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pratyaksh1610** [comment]
Hi @alexvanyo , I have resolved the issue of merging previous commits as mentioned in https://github.com/android/nowinandroid/pull/215#pullrequestreview-1069047532 and did the required changes.
Can I drop a PR for the same ?
