### ISSUE TITLE
[FR]: Investigate using a logging library

### ISSUE THREAD

**Issue by calren** [android/nowinandroid#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

- Should we use a logging library such as Timber? (Related: https://github.com/android/nowinandroid/pull/212)

### Describe the solution

- accompanist uses https://github.com/AAkira/Napier
- iosched / adssched uses Timber

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by StylianosGakis** [comment]
Also consider [logcat](https://github.com/square/logcat), a pretty nice minimal logging library with a very understandable API imo.

**Comment by mmoczkowski** [comment]
Thanks for the idea! The team consensus it that there's very little logging in the app and so there's no justification for using a library at the moment.
