### ISSUE TITLE
[Bug]: Can't Build the Project

### ISSUE THREAD

**Issue by Zikstar** [android/nowinandroid#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

I can't build the project. I'm on Android Studio Electric Eel, Gradle 7.4, Using Java 11. The build keeps failing with the following output

### Relevant logcat output

```shell
> Task :build-logic:convention:compileKotlin
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.compose.gradle.kts: (23, 1): Expression 'android' cannot be invoked as a function. The function 'invoke()' is not found
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.compose.gradle.kts: (23, 1): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
internal val ComPluginGroup.android: ComAndroidPluginGroup defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPlatformPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val PluginDependenciesSpec.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.compose.gradle.kts: (24, 29): Type mismatch: inferred type is Nowinandroid_android_application_compose_gradle but CommonExtension<*, *, *, *> was expected
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.gradle.kts: (24, 1): Expression 'android' cannot be invoked as a function. The function 'invoke()' is not found
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.gradle.kts: (24, 1): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
internal val ComPluginGroup.android: ComAndroidPluginGroup defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPlatformPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val PluginDependenciesSpec.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.gradle.kts: (25, 28): Type mismatch: inferred type is Nowinandroid_android_application_gradle but CommonExtension<*, *, *, *> was expected
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.gradle.kts: (27, 5): Unresolved reference: defaultConfig
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.gradle.kts: (28, 9): Unresolved reference: targetSdk
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.jacoco.gradle.kts: (24, 1): Expression 'android' cannot be invoked as a function. The function 'invoke()' is not found
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.jacoco.gradle.kts: (24, 1): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
internal val ComPluginGroup.android: ComAndroidPluginGroup defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPlatformPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val PluginDependenciesSpec.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.jacoco.gradle.kts: (25, 5): Unresolved reference: androidComponents
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.application.jacoco.gradle.kts: (26, 25): Type mismatch: inferred type is Nowinandroid_android_application_jacoco_gradle but AndroidComponentsExtension<*, *, *> was expected
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.library.compose.gradle.kts: (23, 1): Expression 'android' cannot be invoked as a function. The function 'invoke()' is not found
e: /Users/isaac/AndroidStudioProjects/nowinandroid/build-logic/convention/src/main/kotlin/nowinandroid.android.library.compose.gradle.kts: (23, 1): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
internal val ComPluginGroup.android: ComAndroidPluginGroup defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPlatformPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
internal val PluginDependenciesSpec.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._575eff10af4d8ac420c2c0a93a3cb44b in file PluginSpecBuilders.kt
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by calren** [comment]
Have you tried 'Invalidating cache and restart' option in Android Studio?

**Comment by Zikstar** [comment]
Hi, yes I have tried doing this twice. Still the same errors

**Comment by calren** [comment]
Thanks for the follow up! We're looking into it.

**Comment by ductam1987** [comment]
@Zikstar , I got the same problem & fixed it by upgrading the GradlePlugin from 7.1.2 to 7.1.3

**Comment by Zikstar** [comment]
@ductam1987 Thank you. I can confirm that this solves the problem.

**Comment by Zikstar** [comment]
For anyone facing the problem in the future upgrade "androidGradlePlugin" in the file libs.versions.toml from 7.1.2 to 7.1.3 or later. This makes sense because AGP 7.1.2 is not compatible with Gradle 7.4 which this project specifies in its gradle-wrapper.properties . See https://developer.android.com/studio/releases/gradle-plugin for compatible versions.

**Comment by agent10** [comment]
Changing AGP version to 7.1.3 didn't help me.

**Comment by alexvanyo** [comment]
For those running into this problem, could you share a bit more about your environment?

OS, architecture, JDK version, and whether you're building via command line (`./gradlew`) or inside Android Studio would all be great!

**Comment by Zikstar** [comment]
> Changing AGP version to 7.1.3 didn't help me.

Did you also change your Java version to 11?

**Comment by Zikstar** [comment]
> For those running into this problem, could you share a bit more about your environment?
> 
> OS, architecture, JDK version, and whether you're building via command line (`./gradlew`) or inside Android Studio would all be great!

For me
Mac OS. Intel processor
Android studio electric eel
JDK 11
Only used UI inside of Android Studio

**Comment by agent10** [comment]
> For those running into this problem, could you share a bit more about your environment?
> 
> OS, architecture, JDK version, and whether you're building via command line (`./gradlew`) or inside Android Studio would all be great!

MacOs BigSur 11.3.1, Intel
AS Chipmunk
JDK 11
Building inside AS
Tried "Invalidate cache and restart"

**Comment by alexvanyo** [comment]
Thanks, will try to reproduce here!

**Comment by agent10** [comment]
Weird, what just helped me is to add an empty line to root build.gradle.kts

**Comment by alexvanyo** [comment]
That's very interesting... for building inside Android Studio, are using the "play" button to launch on device? Or the "hammer" "Make project" button?

**Comment by alexvanyo** [comment]
If you are still running into this, a report similar to https://developer.android.com/studio/report-bugs.html with the `idea.log` would be helpful to track down what's going on.

Also, I'd be very interested to know if this is isolated to using the "Make Project" (green hammer) button in AS, and if using the green "Play" button or building via the command line avoids this issue.

**Comment by shashankkapsime** [comment]
> For those running into this problem, could you share a bit more about your environment?
> 
> OS, architecture, JDK version, and whether you're building via command line (`./gradlew`) or inside Android Studio would all be great!

Mac OS 11.5.1, 6-core Intel Core i7
AS Chipmunk 2021.2.1
JDK : Embedded 11.0.12
Building inside AS

**Comment by muhrahmatullah** [comment]
for me, Im changing the gradle jdk version used in AS to used the embed one( version 11.0.11

**Comment by sergpetrov** [comment]
I faced the same issue:
- Mac OS Monterey 12.3.1, Intel
- AS Chipmunk 2021.2.1
- JDK : Embedded 11.0.12
- Building inside of Android Studio and `./gradlew`

Tried all of above and nothing helped (upgrading grdale plugin, invalidating cache).

**Comment by alexvanyo** [comment]
Would it be possible to share the `idea.log` with the building issues through AS?

**Comment by sergpetrov** [comment]
@alexvanyo yes
[idea.log](https://github.com/android/nowinandroid/files/8699251/idea.log)

**Comment by sergpetrov** [comment]
Magic! Today it's building successfully for me after restarting my Macbook.

**Comment by llwdslal** [comment]
I pulled the latest code , everything is ok

**Comment by llwdslal** [comment]
@calren 

I pulled the latest code , everything is ok

**Comment by RivanParmar** [comment]
For me also changing the `androidGradlePlugin` to 7.1.3 resolved the issues.

**Comment by zzy619** [comment]
changing the `androidGradlePlugin` to `7.1.3` and `rm $project/.gradle/  & rm $project build-logic/.gradle/`

**Comment by a25max** [comment]
change 7.1.3 androidGradlePlugin but not work

**Comment by andre-artus** [comment]
> change 7.1.3 androidGradlePlugin but not work
> 
> Android Studio Chipmunk 2021.2.1 jdk: 1.8 OS: monterey
> 
> What I need do?

Change your JDK to11 (or greater)

**Comment by a25max** [comment]
change jdk 11 but not work 😭

**Comment by minhdangoz** [comment]
For everyone who survive with gradle build issue:
- Change the androidGradlePlugin = "7.1.3" > Build again
- If not then change JDK from 1.8 to 11

**Comment by alexvanyo** [comment]
#38 was just merged, which should also help in this area. Please let us know if you're still running into this issue on the latest `main` branch after the updates!

**Comment by shashankkapsime** [comment]
Yes it worked, but now I getting another error : 

> Settings file '/Users/shashank.kapsime/StudioProjects/nowinandroid/build-logic/settings.gradle.kts' line: 25

Using dependency catalogs requires the activation of the matching feature preview.
See the documentation at https://docs.gradle.org/7.1/userguide/platforms.html#sub:central-declaration-of-dependencies

**Comment by HeavyCoffee** [comment]
> Yes it worked, but now I getting another error :
> 
> > Settings file '/Users/shashank.kapsime/StudioProjects/nowinandroid/build-logic/settings.gradle.kts' line: 25
> 
> > Using dependency catalogs requires the activation of the matching feature preview.
> > See the documentation at https://docs.gradle.org/7.1/userguide/platforms.html#sub:central-declaration-of-dependencies

I have the same bug

**Comment by shashankkapsime** [comment]
Hey @alexvanyo, it worked! Thanks!

**Comment by alexvanyo** [comment]
@shashankkapsime can you clarify? Was it #135 that worked for you?

**Comment by shashankkapsime** [comment]
@alexvanyo I just took the pull and I think #135 was already implemented. So it worked for me!

**Comment by alexvanyo** [comment]
Good to hear it worked! #135 hasn't been merged yet, so did you check that branch out specifically? Otherwise if you were on `main`, something else might have resolved it.

**Comment by alexvanyo** [comment]
I'm closing this bug as a few changes have been merged that should address the issues we've seen here.

If you are on the latest version of `main`, and you're still unable to build the project, please open a new bug with a description of what the error is.

Thank you!
