### ISSUE TITLE
[FR]: Consider adding an example of a Kotlin only module

### ISSUE THREAD

**Issue by StylianosGakis** [android/nowinandroid#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Not an issue per se, but with the creating of the new modularization documentation, the section "[Prefer Kotlin & Java modules](https://developer.android.com/topic/modularization/patterns#prefer-kotlin)" talks about how one should prefer modules that are pure Kotlin/Java.

### Describe the solution

It'd be a perfect opportunity for this project to try and include some module which showcases how one would do that to serve as reference for people who want to try it out as well.
It'd also be a great opportunity to add some context in the ModularizationLearningJourney.md file regarding how a pure Kotlin only module is different from one that includes Android and what one has to do differently for a module to be considered pure Kotlin, like removing the android gradle plugin, the manifest etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
`core-model` already is, but we could expand upon it more in documentation and highlight the differences.

**Comment by StylianosGakis** [comment]
Ah I tried to look through them to see if any is but I completely missed `core-model`, thanks for the heads up!
Feel free to close this issue. Unless you want to keep it open to track these potential updates in the documentation 👍
