### ISSUE TITLE
[Bug]: Multiple clicks at the same time

### ISSUE THREAD

**Issue by KristapsKrumins** [android/nowinandroid#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

There are some UI elements that should not be allowed to be clicked at the same time. For example interest badge.
<img src="https://user-images.githubusercontent.com/16702487/186411862-7a64c643-f8fb-49f1-ac15-6a9e2f6f4530.png" width="400">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
FYI this is no longer the case on the current build. Not sure when this was fixed though.

**Comment by calren** [comment]
Thanks @SimonMarquis for verifying. Closing this issue.
