### ISSUE TITLE
[Bug]: Splash screen does not display icon on Android 12

### ISSUE THREAD

**Issue by StylianosGakis** [android/nowinandroid#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

On a `Samsung S20 FE 5G` running:
One UI 4.1
Android 12

When I run the app I see no image showing up on the splash screen. To double check I changed [this](https://github.com/android/nowinandroid/blob/063965c9cd26c62fa029cc2683f08565483f77b5/app/src/main/java/com/google/samples/apps/nowinandroid/MainActivity.kt#L42) line of code from `installSplashScreen()` to `installSplashScreen().apply { this.setKeepOnScreenCondition { true } }` and then I got these two screenshots from the splash screen, in dark and light mode respectively.
| dark | light |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/44558292/187050226-81de125c-b2e8-4a93-828f-bef188748988.png) | ![image](https://user-images.githubusercontent.com/44558292/187050228-3041dfe8-ffb0-4a2b-a9d5-1b925927b39c.png) |

Is there something I'm misunderstanding from the splash compat library, or is this a bug in the implementation in NiA?
As far as I understand, for older android versions, it simply does not support animated icons, but from API 23 and onwards it should still show the icon at least.

For the record, I did also test this on a Pixel 6 Pro running Android 13 and the icon showed up perfectly fine in both dark and light mode.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdityaBavadekar** [comment]
I noticed this issue during my app's first run. And it was working fine later on. This might be an issue 
with the SplashScreenApi.

**Comment by StylianosGakis** [comment]
You're right! This does seem to show after I explicitly close the app and open it again, and not rerunning from AS (as I was doing before).
This feels like quite a big issue if it's a problem with the 1.0.0 version of the `androidx.core:core-splashscreen` library.
I think I'll file a bug, feels quite important tbh.

**Comment by StylianosGakis** [comment]
https://issuetracker.google.com/issues/244063660

**Comment by alexvanyo** [comment]
Hey, thanks for the investigation!

Do you know if this occurs only when launching the app through Android Studio directly?

For example, if you install directly (`./gradlew :app:installDemoDebug`) and then launch from the launcher, does that show the icon?

**Comment by StylianosGakis** [comment]
Hmm very good question, I just tried it and it does indeed seem like if you do that and simply click on the app icon to launch it there is no such bug, the splash screens shows correctly.

So in the end, for people installing the app normally this should be a non-issue, but it may be more of a dev experience annoyance. Very good to know, I will give this information in the ticket too! And it seems like we can close this ticket here since there's nothing wrong with the implementation of the splash screens in this repository.

**Comment by StylianosGakis** [comment]
And it turns out it may not even be a dev-only bug, but a feature of AS. Really caught me off-guard tbh, was not expecting this to happen and I was certain there was something wrong in the configuration at first 🤷‍♂️

**Comment by alexvanyo** [comment]
Agreed, it's not a great iterative experience when trying it out from AS during the normal workflow and not seeing the expected behavior.

I don't think NiA is doing anything incorrect here, so I'm going to close this issue in favor of the upstream ones.

Thanks again for the issue!
