### ISSUE TITLE
[Bug]: UI Jank in the 'For you' screen

### ISSUE THREAD

**Issue by surajsau** [android/nowinandroid#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Whenever the `InterestsSelection` is visible in the 'For you' screen, scrolling back to the `InterestsSelection` always janks heavily. Even the side scrolling of `TopicSelection` janks.

https://user-images.githubusercontent.com/5493586/168229747-17eafc4c-cc53-494e-92b5-894bc877cf9d.mp4

I'm observing this on Pixel 4a device.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by calren** [comment]
I believe this is expected on debug builds. More about that here: https://developer.android.com/jetpack/compose/performance#build-release

Are you able to reproduce the same behavior on a release build?
