### ISSUE TITLE
Use of "destination" property In TopLevelDestination

### ISSUE THREAD

**Issue by joreilly** [android/nowinandroid#265]
It seems like `destination` property is redundant in `TopLevelDestination`...looks like it's mostly there because it has to be overridden from `NiaNavigationDestination`?  Was applying NowInAndroid approach to project here and was just confused by it being set in `NiaAppState` for example but seemingly not used.

**Comment by joreilly** [comment]
More of feedback than issue per se so definitely feel free to close this.

**Comment by dturner** [comment]
Thanks for the feedback (and apologies for the delay in responding). 

`TopLevelDestination` has now been refactored and `destination` has been removed.
