### ISSUE TITLE
[Bug]: Issue with CenterAlignedTopAppBar background color after updating Compose Material 3 to 1.0.0-beta02

### ISSUE THREAD

**Issue by joreilly** [android/nowinandroid#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

I updated my own project to Compose Material 3 1.0.0-beta02 and noticed issue with background color of CenterAlignedTopAppBar....did same thing with NowInAndroid and see same issue (as shown here).  Not sure if this should be reported here or somewhere else?  Seems to have happened between beta1 and beta2.

![Screenshot_20220907_233935](https://user-images.githubusercontent.com/6302/188996157-8b51be2d-167f-46e4-8513-ddedde334cbb.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
I'm guessing you're seeing the same issue as https://issuetracker.google.com/issues/245575782?

There was a change that was first released on `1.0.0-beta02` that prevents creating a top app bar with a transparent background (like we do in Now in Android), as it will instead display the underlying `Surface` with its default color.

**Comment by joreilly** [comment]
Thanks, will keep an eye out to see changes made to NowInAndroid to address this and will update to beta2 then :)

**Comment by joreilly** [comment]
Though looks from https://issuetracker.google.com/issues/245575782 that this is being addressed in the library?

**Comment by alexvanyo** [comment]
Yes, https://android-review.googlesource.com/c/platform/frameworks/support/+/2209896/ just merged, which should be in the next release.

You can also try out the latest snapshot as well, I have a draft PR for that in NiA here: https://github.com/android/nowinandroid/pull/242

**Comment by alexvanyo** [comment]
Closing since the issue was upstream and the fix has been merged.
