### ISSUE TITLE
[Documentation]: The dependencies is redundant, can the dependencies be simplified?

### ISSUE THREAD

**Issue by lelelongwang** [android/nowinandroid#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Page URL (type "NEW" for a new page suggestion)

NEW

### What's the documentation problem or suggestion?

":core:data" implementation ":core:model" and ":core:database"，":core:database" implementation ":core:model"，The dependencies is redundant, can the dependencies be simplified?

![Diagram showing types of modules and their dependencies in Now in Android](images/modularization-graph.drawio.png "Diagram showing types of modules and their dependencies in Now in Android")

In the above diagram, the dependencies of the "core" part are confusing, can you optimize it?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
Image is broken and I'm not entirely sure what is being suggested. Please open a new issue with more details if this is still relevant.
