### ISSUE TITLE
[FR]: Add Support for Bazel

### ISSUE THREAD

**Issue by alyssa-nash** [android/nowinandroid#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

From my understanding, Bazel was made specifically for this use case of a multi-module, monolithic repo and is a great alternative to Gradle in this use case thanks to faster build speed. I am currently looking into Bazel as an option for my use cases, and am trying to learn and find great examples of its use. 

### Describe the solution

Would it be possible to add Bazel to this project to showcase its use with these modular applications?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mmoczkowski** [comment]
Hey Alyssa, thanks for the request. Gradle is the official build system for Android and we don't really have plans for supporting anything else at the moment. I'm not sure if Bazel would be a good choice for Now in Android since it was intended for much larger projects (that take hours to build).

**Comment by alyssa-nash** [comment]
Yeah after doing some research over the weekend, I can see why gradle is official. Thanks for the info!
