### ISSUE TITLE
[Bug]: App is Lagging(scroll feels like it is stuck) on ForYouScreen and BookmarksScreen even with the release build and baseline profiles

### ISSUE THREAD

**Issue by sunildhiman90** [android/nowinandroid#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

A bug happened!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by keyboardsurfer** [comment]
Thanks. While we'd like to address the issue you faced we are missing key information on how to reproduce the issue.
To get started, please let me know if you used a `debug` or `release` build.
Also, please attach relevant logs from `adb logcat` when you're reproducing this issue.

**Comment by sunildhiman90** [comment]
Hi Thanks for reply, Actually i am using demo release build,  And you can reproduce it every time by scrolling after selecting some authors on home screen, then that scrolling is not smooth on For You Screen and Saved Screen(after saving some items) , it stucks in between while scrolling

My device Model is Samsung
Model name: Galaxy M31
Model Number: SM-M315F/DS
Android Version: 12

Following are the attached logs while i was scrolling:
[now_in_android_logs.txt](https://github.com/android/nowinandroid/files/9714976/now_in_android_logs.txt)

**Comment by keyboardsurfer** [comment]
Thanks! I found several reports of jank in the `forYou` section.

```
16:09:20.037  V  FrameData(frameStartNanos=15829427875822, frameDurationUiNanos=199191855, frameDurationCpuNanos=203876125, frameOverrunNanos=197468343, isJank=true, states=[forYou:feed: Scrolling=true, Navigation: for_you_route])
16:09:20.050  V  FrameData(frameStartNanos=15829627067677, frameDurationUiNanos=195526156, frameDurationCpuNanos=198859771, frameOverrunNanos=174146208, isJank=true, states=[forYou:feed: Scrolling=true, Navigation: for_you_route])
16:09:22.036  V  FrameData(frameStartNanos=15831465736121, frameDurationUiNanos=175238285, frameDurationCpuNanos=178293054, frameOverrunNanos=145149415, isJank=true, states=[forYou:TopicSelection: Scrolling=true, Navigation: for_you_route]
16:09:22.242  V  FrameData(frameStartNanos=15831699573219, frameDurationUiNanos=128801534, frameDurationCpuNanos=137903919, frameOverrunNanos=128206214, isJank=true, states=[forYou:TopicSelection: Scrolling=true, Navigation: for_you_route])
16:09:26.330  V  FrameData(frameStartNanos=15835891911868, frameDurationUiNanos=34353651, frameDurationCpuNanos=38311689, frameOverrunNanos=29789254, isJank=true, states=[forYou:feed: Scrolling=true, Navigation: for_you_route])
```

**Comment by keyboardsurfer** [comment]
Added more Jank tracking in #328. We'll have to continue investigating here.

**Comment by dturner** [comment]
Closing as stale. Please open a new issue if you're still experiencing this issue.
