### ISSUE TITLE
[FR]: provide example of adaptive content layouts

### ISSUE THREAD

**Issue by joreilly** [android/nowinandroid#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Provide example of adaptive content layouts e.g. list-detail layout on wider screens.

### Describe the solution

This would be along the lines of what's described for example in https://developer.android.com/jetpack/compose/layouts/adaptive.  I realise JetNews has example of this right now but would be useful in this app to show how this might be achieved given approach used for navigation in this project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joreilly** [comment]
Potentially using `TwoPane` layout from https://google.github.io/accompanist/adaptive/

**Comment by alexvanyo** [comment]
Initial support added in #1234

**Comment by XiaomiTpro** [comment]
> Initial support added in #1234 

- [ ] []()
