### ISSUE TITLE
The `libs` error in the some build.gradle

### ISSUE THREAD

**Issue by SaeedNoshadi89** [android/nowinandroid#34]
I see an error with `libs` in some `build.gradle` files.

The error is obvious below files:
`build.grdle.kts (:code-database)`
`build.grdle.kts (:code-datastore)`
`build.grdle.kts (:code-model)`
`build.grdle.kts (:code-navigation)`

![Screen Shot 2022-05-14 at 17 04 39](https://user-images.githubusercontent.com/50018300/168426259-c79d5dbe-d4b8-441d-b7a2-c4b362c7b93e.png)

**Comment by alexvanyo** [comment]
Suppressed this warning in #35
