### ISSUE TITLE
[Bug]: Ripple effect on `NavigationBarItem` has been disabled on the app

### ISSUE THREAD

**Issue by SimonMarquis** [android/nowinandroid#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

It doesn't seem expected to remove this pressed/focus effect.
Should we open a PR to restore the default Ripple theme?

https://github.com/android/nowinandroid/blob/ef42543b32b58038fbe5cdcee17af8fe69756ad7/app/src/main/java/com/google/samples/apps/nowinandroid/ui/NiaApp.kt#L152

https://user-images.githubusercontent.com/1921278/168426947-100775b0-e626-4211-b55a-95c7ae537c81.mp4

---

Note: It's working as expected on the [app-nia-catalog](https://github.com/android/nowinandroid/tree/main/app-nia-catalog).

https://user-images.githubusercontent.com/1921278/168426950-4aa08886-5f46-4155-9c3c-1fa22c786f43.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RivanParmar** [comment]
@SimonMarquis The current version of the project already has the line of code that you posted. However, the ripple effect is still not working. It would be great to have it.

**Comment by SimonMarquis** [comment]
@RivanParmar indeed, the current code provides a `ClearRippleTheme` which is transparent:

https://github.com/android/nowinandroid/blob/c6397715d34b7f7795ca275c1bd3b77d6c285179/core-ui/src/main/java/com/google/samples/apps/nowinandroid/core/ui/ClearRippleTheme.kt#L24-L36

That is the reason why I proposed to removed this to restore the default ripple behavior.

**Comment by RivanParmar** [comment]
> @RivanParmar indeed, the current code provides a `ClearRippleTheme` which is transparent:
> 
> https://github.com/android/nowinandroid/blob/c6397715d34b7f7795ca275c1bd3b77d6c285179/core-ui/src/main/java/com/google/samples/apps/nowinandroid/core/ui/ClearRippleTheme.kt#L24-L36
> 
> That is the reason why I proposed to removed this to restore the default ripple behavior.

I agree with you that the default ripple behaviour should be restored. So that the users would know which button they clicked.
