### ISSUE TITLE
Change `UserData` to `UserPreferences`

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#377]
"Preferences" more accurately describes the data [this model](https://github.com/android/nowinandroid/blob/main/core/model/src/main/java/com/google/samples/apps/nowinandroid/core/model/data/UserData.kt) contains. 

Also requires changing the `*UserDataRepository` objects to `*UserPreferencesRepository`

**Comment by vaishnav-mk** [comment]
I'm quite new to this so I'd like to confirm the following:
- you want all mentions of `UserData` to be changed to `UserPreferences`
- same as above, all `UserDataRepository` mentions should be changed to `UserPreferencesRepository`
did I get it right?

**Comment by MohNage7** [comment]
@dturner renaming `UserData` to `UserPreferences` will conflict with `com.google.samples.apps.nowinandroid.core.datastore.UserPreferences` that's generated by `user_preferences.proto` 
I think we should pick another name 🤔

**Comment by dturner** [comment]
Thanks both for your interest in this issue. The thinking behind this is the type of data stored in this class: 

```
data class UserData(
    val bookmarkedNewsResources: Set<String>,
    val followedTopics: Set<String>,
    val followedAuthors: Set<String>,
    val themeBrand: ThemeBrand,
    val darkThemeConfig: DarkThemeConfig,
)
```

Should we describe this as:

- `UserPreferences` and potentially rename `datastore.UserPreferences` to avoid a clash (thanks for pointing this out @MohNage7 ). Another issue is that on Android the term `preferences` is already a commonly used term e.g. `SharedPreferences`.  
- something else. Open to suggestions.  
- keep as `UserData`?

**Comment by MohNage7** [comment]
@dturner Thanks for your reply. 
IMHO, I think we can rename the proto class to `UserPreferencesStore` or `UserPreferencesCache` or go with the last option and leave `UserData` as is. Please let me know WDYT?

**Comment by camina-apps** [comment]
How about changing the name `UserData` to `UserSettings`?

**Comment by dturner** [comment]
Thanks for the suggestions. I'm inclined to leave as-is for now. It's likely that we'll store other information here in future and `UserData` is generic enough to accommodate that.
