### ISSUE TITLE
[FR]: Have `FakeDataSource` load from JSON files rather than hardcoded data

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Hardcoding JSON data into `FakeDataSource` makes it difficult to update and not very readable. It'd be better to have the JSON data stored as assets or resources in the app, then read and parsed by an `AssetsDataSource` or similar. 

Context: https://github.com/android/nowinandroid/pull/387#discussion_r1014004896

### Describe the solution

- Create JSON files for topics, authors and news resources (this is the output of the spreadsheet script)
- Store these files as resources or assets in the app package
- Create a data source which can read and parse these files

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yveskalume** [comment]
How can this be done ? since reading a json file from assets folder has a little complexity.

**Comment by SimonMarquis** [comment]
👋 Hi, I've created a draft PR https://github.com/android/nowinandroid/pull/417 to demonstrate a potential solution for this issue (with minimal changes to the source code).
Tell me waht you think about it.
