### ISSUE TITLE
[FR]: Sort authors by how many resources they have written

### ISSUE THREAD

**Issue by JolandaVerhoef** [android/nowinandroid#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Currently, authors are sorted alphabetically, which leads to a lot of noise (someone who has written a single article might end up more prominently than someone that has written many). 

### Describe the solution

Should we consider sorting them by number of resources added?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yveskalume** [comment]
Is there an optimised way to get the author's resources.

**Comment by alexvanyo** [comment]
Closing with the removal of authors.
