### ISSUE TITLE
[Bug]: Unresolved reference: com.android.build

### ISSUE THREAD

**Issue by JakubMosakowski** [android/nowinandroid#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Imports in convention plugins are not resolved. The project builds and works but it is a minor inconvenience in usage. 

Android Studio Dolphin | 2021.3.1

I tried all those simple steps, like cleaning the project, cache etc.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/23456332/200869254-b7b30ef6-6257-43e4-8b57-a56943516868.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
Could you recheck if this is still the case now that we upgraded to AGP 8?

**Comment by SimonMarquis** [comment]
I think this issue can be closed.

**Comment by alexvanyo** [comment]
Closing, please open a new issue if you're still running into a problem with the latest versions of Android Studio.
