### ISSUE TITLE
[Bug]: Onboarding "Done" text is tiny

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

The text on the "Done" button is tiny. It shouldn't be. 

![Screenshot_20221110-130133](https://user-images.githubusercontent.com/873212/201103458-68dfbfb0-7dae-4bdc-815f-fc7167411744.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
What would be the appropriate style?

https://github.com/android/nowinandroid/blob/e72e31b1f013676a10b4ecc6f83606a51141e862/feature/foryou/src/main/java/com/google/samples/apps/nowinandroid/feature/foryou/ForYouScreen.kt#L270-L272

`MaterialTheme.typography.bodyMedium` maybe?

**Comment by SimonMarquis** [comment]
| Default | `bodySmall` | `bodyMedium` | `bodyLarge` |
|---|---|---|---|
| ![image](https://user-images.githubusercontent.com/1921278/201416368-513a08fb-b5d1-4b46-ac07-f1d6ab8bffc3.png) | ![image](https://user-images.githubusercontent.com/1921278/201416491-feb9644d-1f21-45cf-9411-781ade476b28.png) | ![image](https://user-images.githubusercontent.com/1921278/201416421-8b284093-be12-42fd-8ee6-2cd8e3d910f0.png) | ![image](https://user-images.githubusercontent.com/1921278/201416647-81772afe-b64d-400b-8b48-f3c986461e9c.png) |

**Comment by SimonMarquis** [comment]
Though it seems like the `NiaFilledButton` (and `NiaOutlinedButton`) are always using `MaterialTheme.typography.labelSmall` without checking the value of the boolean parameter `small`.

https://github.com/android/nowinandroid/blob/e72e31b1f013676a10b4ecc6f83606a51141e862/core/designsystem/src/main/java/com/google/samples/apps/nowinandroid/core/designsystem/component/Button.kt#L73-L77

Maybe the better fix would be to do:

```diff
        content = {
-            ProvideTextStyle(value = MaterialTheme.typography.labelSmall) {
+            ProvideTextStyle(value = if(small) MaterialTheme.typography.labelSmall else MaterialTheme.typography.labelMedium) {
                content()
            }
        }
```

**Comment by SimonMarquis** [comment]
@dturner this has been fixed, you can close the issue :)
![image](https://github.com/android/nowinandroid/assets/1921278/2ee13f0b-3134-4cff-b46f-fd25f467ba63)

**Comment by SimonMarquis** [comment]
This issue has been fixed, we can close the issue.
