### ISSUE TITLE
[Bug]: Author first names are wrapped onto multiple lines

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

The author first names in the onboarding are wrapped onto multiple lines if their first name is longer than ~8 characters
<img width="363" alt="image" src="https://user-images.githubusercontent.com/873212/201106039-38f412ed-95c3-4e95-84ee-187c7f6c5e88.png">
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
Closing with the removal of authors.
