### ISSUE TITLE
[Bug] For You shows articles from authors you're not following

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#409]
Steps to repro in 0.0.3: 

- Tap on Jolanda
- Scroll down

Expected result: 

- All news resources are authored by Jolanda

Actual result: 

- The 3rd news resource is authored by Anna

Cause: The NewsResourceCard shows only a single author. In the case above the news resource is authored by Jolanda _and_ Anna, but only Anna is shown. This is confusing for users. 

Solution: Show all authors (maybe first name only if we're limited on space) in the news resource card.

**Comment by SaeedNoshadi89** [comment]
I fix this on #431

**Comment by calren** [comment]
Fixed in PR linked above
