### ISSUE TITLE
[Bug]: Consistent naming convention for NiANetwork and NiaPreferences etc

### ISSUE THREAD

**Issue by joreilly** [android/nowinandroid#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Not a bug per se, and probably super picky :) , but be nice to have consistent naming convention e.g. for `NiANetwork` (big A) and `NiaPreferences` (little a)....only noticed this when reading https://github.com/android/nowinandroid/blob/main/docs/ArchitectureLearningJourney.md as I didn't realise initially  what `NiA` stood for!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sud007** [comment]
@joreilly I have added a PR if that can be reviewed to fix this. Thank you!
