### ISSUE TITLE
The Bookmarks screen should show "No bookmarks" instead of a blank screen

### ISSUE THREAD

**Issue by RivanParmar** [android/nowinandroid#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Currently the Bookmarks screen remains empty when you haven't bookmarked any articles. It feels as if the screen might be loading content. This should not happen. The screen should instead show some text such as "No articles bookmarked" or "Bookmarks will appear here" or something like that.

![Screenshot_20221111-141845](https://user-images.githubusercontent.com/77159650/201302398-c08270a4-c510-4053-8e66-fc568d134287.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LinX64** [comment]
That's a good point!

They basically added [`Loading`](https://github.com/android/nowinandroid/blob/main/core/ui/src/main/java/com/google/samples/apps/nowinandroid/core/ui/NewsFeed.kt#L80) as an `object` as well as [`Success`](https://github.com/android/nowinandroid/blob/main/core/ui/src/main/java/com/google/samples/apps/nowinandroid/core/ui/NewsFeed.kt#L85) as a `data class` and they are showing the data once available without any checks for the availability of data.

**Solution:**

- The first idea is to add `Empty` as an `object` inside the sealed interface and handle the empty data inside the view:

```
sealed interface NewsFeedUiState {
    
    /**
     * The feed is still loading.
     */
    object Loading : NewsFeedUiState

    /**
     * The feed is empty.
     */
    object Empty : NewsFeedUiState

    /**
     * The feed is loaded with the given list of news resources.
     */
    data class Success(
        /**
         * The list of news resources contained in this feed.
         */
        val feed: List<SaveableNewsResource>
    ) : NewsFeedUiState
}
```

- Another option is to count the retrieved data inside the view and by the `Success` data class and then showing a `Text` based on `count == 0`. I will create a PR for this.

Let me know your thoughts :)

**Comment by calren** [comment]
Fixed in https://github.com/android/nowinandroid/pull/427 I believe
