### ISSUE TITLE
[FR]: Add :app:wear to the project

### ISSUE THREAD

**Issue by pitoszud** [android/nowinandroid#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

By adding wear to the project you could cover all form factors (small, medium, large and wear). You could also show an architecture where :app:mobile and :app:wear are sharing :domain:feature modules and :data:some-other-feature.

This could be either a simple or quite versatile wear app, focusing on compose, communication and sharing modules between mobile and wear.
We've got some samples covering this in wear-os-samples, but I think nowinandroid is modularized well enough to accommodate :app:wear, so why not?

https://github.com/android/wear-os-samples/tree/main/DataLayer
https://github.com/android/wear-os-samples/tree/main/RuntimePermissionsWear

![image](https://user-images.githubusercontent.com/13464778/201659120-657d7915-8ab6-4f89-a057-6d05cbe3fa5a.png)

### Describe the solution

I would add :app:mobile and update app module to :app:wear. Gradle should be updated accordingly. 
Perhaps the domain should be moved outside of core. Some, but not all data, should be shared between mobile and wear.

bdw, "domain" is missing in the readme common module representation.
https://github.com/android/nowinandroid/tree/main/core/common

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pitoszud** [comment]
Below are some ideas to represent basic data sharing communication between mobile and wear.
This could be something very similar to Google Keep

**Mobile**
Interest (visible and controlled in mobile only)


**Wear**


_ForYou_
- User can see a full title and shorter description.
- User can save a news item to bookmarks and then read/watch on mobile later.

_Saved_
- User can browse bookmarked news
- User can tap on "Open on mobile" text/button and open the content on mobile
- Optional (User can unfollow the topic) - mobile is updated accordingly

_Notification_
- new content (although this would be difficult to implement with a static resource)

_Settings_
- Limit items to e.g. 10, 50, 100
- Enable LTE (if exists) - this would require the wear to have its own news resource representation
- Bluetooth/Wi-Fi selected by default would share connection/data with mobile after pairing.

**Comment by yschimke** [comment]
A big hearty +1 - I know product wise it isn't obvious. But in terms of applied modularity and also play store publishing, this will really help to have a wear app.

**Comment by mmoczkowski** [comment]
Hey folks, check the prototype I made.

![PXL_20221118_175714302 TS 3](https://user-images.githubusercontent.com/6339497/202774445-60dbb0ad-a5fb-4e12-9cf6-fe129b85c443.gif)
