### ISSUE TITLE
[Bug]: Could not resolve all files for configuration ':app:androidApis'.

### ISSUE THREAD

**Issue by 10sp** [android/nowinandroid#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

A bug happened!,

### Relevant logcat output

```shell
Could not resolve all files for configuration ':app:androidApis'.
Failed to transform android.jar to match attributes {artifactType=android-mockable-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, returnDefaultValues=false}.
Execution failed for MockableJarTransform: C:\Users\Error\AppData\Local\Android\Sdk\platforms\android-33\android.jar.
Cannot create mockable android.jar
C:\Users\Error\AppData\Local\Android\Sdk\platforms\android-33\android.jar
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
@10sp are you still able to reproduce the issue? Otherwise I think we can close this issue.
