### ISSUE TITLE
[Bug]: [Documentation]: Most of the code is written under src/main/java although its Kotlin

### ISSUE THREAD

**Issue by khalid64927** [android/nowinandroid#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Since this is Android Showcase project It would be good to keep all codebase (which is in Kotlin) in relevant folder name (src/main/kotlin , src/test/kotlin, src/androidTest/kotlin)

The legacy naming  for modules which is by default from IntelliJ ( src/main/java ) seems obsolete.

<img width="245" alt="Screenshot 2022-11-15 at 7 43 19 PM" src="https://user-images.githubusercontent.com/2426309/201911410-098a2946-7e2e-4dda-85f1-09c9958e2e4d.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sumanabhi** [comment]
If anyone doesn't take this, then I can assign this to myself and make some contributions.

**Comment by dturner** [comment]
Feel free to take this - thanks.

**Comment by RivanParmar** [comment]
Is this issue still open for contribution? If yes, then I would like to work on it!

**Comment by Avinashdindial** [comment]
Plz do

Sincerely,

Avinash Dindial

**Comment by dturner** [comment]
This has been fixed. 
![image](https://github.com/android/nowinandroid/assets/873212/0409680e-3abe-4f66-876d-5db049256ed2)
