### ISSUE TITLE
[Filename Sanity]: NiAApp.kt vs ui/NiaApp.kt

### ISSUE THREAD

**Issue by mebelz** [android/nowinandroid#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

In app/src/main/java/com/google/samples/apps/nowinandroid/ there is NiAApp.kt, whereas in ui/ there's NiaApp.kt.
Since one of the the app's goals is to "showcase best practices", maybe one of those files should be renamed? (hopefully not to the other's, but to a new unique name?)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sud007** [comment]
@mebelz I have added a PR to normalise the naming convention for Nia.
