### ISSUE TITLE
Unresolved reference: libs

### ISSUE THREAD

**Issue by BlueSky15171** [android/nowinandroid#459]
studio：Flamingo 2022.2.1 Canary8
os:macOS Ventura 13.0
jdk: android studio jbr
--------------------------------------------------
Build file '/Users/sky/Desktop/nowinandroid2/build.gradle.kts' line: 29

* What went wrong:
Script compilation errors:

  Line 29:     alias(libs.plugins.android.application) apply false
                     ^ Unresolved reference: libs

  Line 30:     alias(libs.plugins.kotlin.jvm) apply false
                     ^ Unresolved reference: libs

  Line 31:     alias(libs.plugins.kotlin.serialization) apply false
                     ^ Unresolved reference: libs

  Line 32:     alias(libs.plugins.hilt) apply false
                     ^ Unresolved reference: libs

  Line 33:     alias(libs.plugins.secrets) apply false
                     ^ Unresolved reference: libs

5 errors

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 183ms

**Comment by dturner** [comment]
Please could you describe the exact steps you used to start the build process.

**Comment by BlueSky15171** [comment]
> Please could you describe the exact steps you used to start the build process.

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/11631053/203769009-4a26705a-a1a7-45b6-a1b0-854d342fa7c7.png">
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/11631053/203769240-713090f0-77f8-4fd2-8f65-d83452bea255.png">

**Comment by dturner** [comment]
Sorry I still don't understand what you're doing. Please could you describe, in words, the exact steps which you're taking to encounter this error, starting with how you're cloning the repository.

**Comment by sinyotok** [comment]
i have the same problem with my android studio iguana version.
i create project with android studio iguana version, after done with my project, i reinstall my pc and android studio with same version, then i open my project i created before i goth this error.

**Comment by liangchaojiang** [comment]
> ## studio：Flamingo 2022.2.1 Canary8
> os:macOS Ventura 13.0
> jdk: android studio jbr
> Build file '/Users/sky/Desktop/nowinandroid2/build.gradle.kts' line: 29
> 
> * What went wrong:
>   Script compilation errors:
>   Line 29:     alias(libs.plugins.android.application) apply false
>   ^ Unresolved reference: libs
>   Line 30:     alias(libs.plugins.kotlin.jvm) apply false
>   ^ Unresolved reference: libs
>   Line 31:     alias(libs.plugins.kotlin.serialization) apply false
>   ^ Unresolved reference: libs
>   Line 32:     alias(libs.plugins.hilt) apply false
>   ^ Unresolved reference: libs
>   Line 33:     alias(libs.plugins.secrets) apply false
>   ^ Unresolved reference: libs
> 
> 5 errors
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 183ms

头像是本人么

**Comment by anhtuannd** [comment]
@liangchaojiang 
NIA now uses AGP versioned 8.7.3, API level 35 so I think you need to upgrade Android Studio from Flamingo 2022.2.1 to at least Koala Feature Drop 2024.2.1

See also: https://developer.android.com/studio/releases#api-level-support
