### ISSUE TITLE
How do we access token stored locally in RetrofitNiaNetwork?

### ISSUE THREAD

**Issue by tapandesai** [android/nowinandroid#462]
So here is the scenario.

The api call needs authentication, auth token is stored locally and needs to be added in request header.

In this code structure network module is unaware of local (datastore) module.

How do we add auth token (stored locally) using interceptor in network module?

**Comment by Egi10** [comment]
You can add injection datastore in RetrofitNiaNetwork interceptor untuk headernya.

**Comment by dturner** [comment]
We are using https://developers.google.com/maps/documentation/android-sdk/secrets-gradle-plugin to store the backend URL which we use for testing. We haven't merged the authentication code yet so aren't ready to discuss that.

**Comment by tapandesai** [comment]
@dturner I am not talking about backend url. I was talking about `authentication token` which is stored locally in datastore.

Since datastore and network are two separate module which cannot be referred to and from. How do I get the auth token which is supposed to be added in the request header using interceptor?
