### ISSUE TITLE
[Bug]: When the NavRail is showing, the title in the app bar is not centered with the rest of the app content

### ISSUE THREAD

**Issue by alexvanyo** [android/nowinandroid#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

The "Now in Android" title is not centered with the onboarding text, which differs from our [designs](https://www.figma.com/community/file/1164313362327941158):

![Screenshot_20221205_131852](https://user-images.githubusercontent.com/4217560/205773962-49aa5109-fbb8-4ac4-8c3e-874718559f42.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lihenggui** [comment]
According to the layout inspector result, the Toolbar is covered by the NavigationRail. It's not content centered, it is screen centered.
