### ISSUE TITLE
[Bug]: InterestsTabState unused

### ISSUE THREAD

**Issue by pitoszud** [android/nowinandroid#486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Not really a bug, but unused StateFlow in one of the ViewModels.
The StateFlow below is as state of tabs (title and currentIndex) in the InterestsViewModel; however, it is not being used anywhere as far as I'm aware.

It seems that you had tabs in the previous versions in e.g foldable, landscape, but you removed it in the current version?

```
private val _tabState = MutableStateFlow(
        InterestsTabState(
            titles = listOf(R.string.interests_topics, R.string.interests_people),
            currentIndex = 0
        )
    )
    val tabState: StateFlow<InterestsTabState> = _tabState.asStateFlow()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
That's correct, this code should be removed. Thanks for filing this.
