### ISSUE TITLE
Update screenshots now that authors have been removed

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#505]

**Comment by dturner** [comment]
Best to take screenshots on API 11 as this uses the default theme without dynamic color.

**Comment by MudssirAhmed** [comment]
Hey, @dturner It's Mudssir Ahmed and Android Developer, I want to contribute in this project, If possible you can assign it to me. 
Thank you!

**Comment by dturner** [comment]
Hi @MudssirAhmed, sorry for the delay in responding. Someone else took this in the end, hopefully you can find another issue to work on.
