### ISSUE TITLE
Project doesn't build on Android Studio Arctic Fox

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#518]
Which is the earliest version of AS which we support? Specify this prerequisite in the docs.

**Comment by alexvanyo** [comment]
In the main README we mention to use the latest stable version of Android Studio, which is currently Dolphin: https://github.com/android/nowinandroid#development-environment, and that matches up with our current AGP version (`7.3.1`) which requires Dolphin or higher. Maybe we should mention it by name explicitly, with the downside of having to remember to update it whenever we upgrade AGP?

**Comment by SimonMarquis** [comment]
We currently define the required version like this:

https://github.com/android/nowinandroid/blob/b989d3a243d09e40fadaba1264ea20d7df89e362/README.md?plain=1#L33

I think this is good enough. Could we close the issue?
