### ISSUE TITLE
[FR]: Upgrade sourceCompatibility and targetCompatibility to Java 17

### ISSUE THREAD

**Issue by angiesasmita** [android/nowinandroid#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Currently sourceCompatibility and targetCompatibility targets Java 8. This might have resulted in cryptic error message for bug: https://github.com/android/nowinandroid/issues/527 and build and runtime performance penalty

### Describe the solution

- Upgrade sourceCompatibility and targetCompatibility to target java 17
- Check if there's build time improvement
- Check if there's any regression issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdnanHabibMirza** [comment]
Hi @dturner, I would like to contribute to it.

**Comment by chanjungkim** [comment]
Isn't that easy issue??

**Comment by lihenggui** [comment]
> 

No, it isn't that easy. It will throw multiple errors.

```
No matching variant of project :build-logic:convention was found. The consumer was configured to find a runtime of a library compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.6' but:
Variant 'apiElements' capability com.google.samples.apps.nowinandroid.buildlogic:convention:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares an API of a component compatible with Java 17 and the consumer needed a runtime of a component compatible with Java 11
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '7.6')
             - Variant 'mainSourceElements' capability com.google.samples.apps.nowinandroid.buildlogic:convention:unspecified declares a component, and its dependencies declared externally:
               ...
```

If you upgrade Gradle you will get other issues.

```
A problem occurred configuring project ':core:datastore'.
> Could not get unknown property 'source' for generate-proto-generateDemoDebugProto of type org.gradle.api.internal.file.DefaultSourceDirectorySet.
```

**Comment by calren** [comment]
I believe this branch is related https://github.com/android/nowinandroid/commits/av/agp-8.1
