### ISSUE TITLE
[FR]: Add swipe gesture to Tabs in Interests screen

### ISSUE THREAD

**Issue by RivanParmar** [android/nowinandroid#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

The Tabs in the Interests screen do not have swipe gestures to move between **Topics** and **People** screens. You have to click on the tabs every time to navigate between the two (which many people I am sure won't like, including me).

### Describe the solution

There should be a swipe navigation available so that you could switch between the **Topics** and **People** screens easily without having to click on the Tabs. The swipe navigation could be implemented using a ViewPager or by manually adding gesture support through `Modifier.swipeable`.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by RivanParmar** [comment]
Also if possible, then I would like to work on it.

**Comment by Dark-Knight11** [comment]
Hi, I would like to work on this feature.

**Comment by rvenky125** [comment]
I am willing to implement this feature if there is issue with the pr.

**Comment by dturner** [comment]
Closing as the "People" tab has been removed (for now).
