### ISSUE TITLE
[Bug]: Multiple fingers can touch the screen at the same time

### ISSUE THREAD

**Issue by nntsl** [android/nowinandroid#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

It is possible to click multiple items at TopicsTabContent once (the same happens with People tab). 
If we press with several fingers at once, all screens will open. Going back we will see all of them.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishesh211** [comment]
@nntsl  I reproduced the bug on my android too. There is this stackoverflow answer for a similar question which uses a extension. I added the code and tested it on my system. It successfully killed the bug and the interests screen was registering one touch at a time. 

I'll paste the link here. You can look it up yourself.
StackOverflow link:-  https://stackoverflow.com/a/72816456

**Comment by vishesh211** [comment]
hi @dturner i am new to this library. I have fixed this bug and created a pull request. Can you guide me on what i need to do next. Thank you it will help me out a lot.

**Comment by chenlong0225** [comment]
Use **launchSingleTop = true**
![image](https://user-images.githubusercontent.com/120089153/227418333-853c9c68-02a8-4464-9552-7e12caec3782.png)
![image](https://user-images.githubusercontent.com/120089153/227418408-8e5fbbe8-fbb4-47c4-a1ed-dcca667ce842.png)
