### ISSUE TITLE
[Bug]: Options Unfollow and Browse topic don't work on tags

### ISSUE THREAD

**Issue by olekstomek** [android/nowinandroid#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Options `Unfollow` and `Browse topic` don't work on tags. I click on these options and there is no action, nothing happens.
![image](https://user-images.githubusercontent.com/26818304/213585954-5a73e07a-0a65-4763-99e2-c76bd11862dc.png)
What's more - it is always `Unfollow` option, I don't follow `HEADLINES` tag so I expect that in option will be `Follow`.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by calren** [comment]
We are changing the behavior of the tags so that tapping on the tag brings the user to the detail page of the tag: https://github.com/android/nowinandroid/pull/540 , so I believe we can safely this bug for now.

**Comment by olekstomek** [comment]
OK, thanks for this info. So, I'm closing this issue.
