### ISSUE TITLE
[Bug]: Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values

### ISSUE THREAD

**Issue by SimonMarquis** [android/nowinandroid#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

It seems like since AGP 7.4.0 a new warning has appeared in build logs: https://github.com/android/nowinandroid/actions/runs/3963986459/jobs/6792427613#step:8:21

Any idea where this comes from, and if it should be taken care of or simply ignored for now?

### Relevant logcat output

```shell
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
I believe this is the same as https://issuetracker.google.com/issues/247906487

**Comment by SimonMarquis** [comment]
Thanks for the link.

> hm...@google.com<hm...@google.com> Feb 6, 2023 01:08PM
> This is should be a fairly easy and risk-free change to cherry pick in 7.4.2. I will get on it.
> https://issuetracker.google.com/issues/247906487#comment16

Let's wait for this 🤞 I don't think suppressing this log on this project is necessary.

**Comment by SimonMarquis** [comment]
Closing as no longer reproduced with AGP 8
