### ISSUE TITLE
[FR]: Improve CI androidTest execution by reordering tasks

### ISSUE THREAD

**Issue by SimonMarquis** [android/nowinandroid#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

The current workflow for androidTest uses `reactivecircus/android-emulator-runner` and a single `gradlew` script.

https://github.com/android/nowinandroid/blob/8a25efabfc55941c2ef099a7496139914612c5bc/.github/workflows/Build.yaml#L85-L93

This means (as you can see in the run [logs](https://github.com/android/nowinandroid/actions/runs/4092168776/jobs/7056940654)) the emulator first boots-up before the gradle can compile, assemble and run the android tests.
This obviously takes aways resources that could be better allocated for the compilation/assembling tasks.

### Describe the solution

Do you think it might be helpfull to run these tasks before launching the emulator?
I was thinking about using the `pre-emulator-launch-script` argument to attempt running the androidTest (or introduce a preceeding step).

This first action will end-up as a failure because of `DeviceException: No connected devices!` but it will still have compile and assemble all the tasks.
Then, re-executing it once the emulator is started, we will benefit from the local cache and all the tasks (excluding the testing tasks) will be `UP-TO-DATE`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
On a local machine, the second `connectedProdDebugAndroidTest` (when a device is actually connected) runs only a few tasks instead of the whole task graph.

```
> gradlew connectedProdDebugAndroidTest

[...]

BUILD FAILED in 1m 40s
1152 actionable tasks: 1147 executed, 5 up-to-date
```

```
> gradlew connectedProdDebugAndroidTest

[...]
BUILD SUCCESSFUL in 1m 41s
1147 actionable tasks: 21 executed, 1126 up-to-date
```

**Comment by alexvanyo** [comment]
This is an interesting issue, and also made doubly interesting with our GMD-based CI where we currently restrict max workers to 1 for GMD to work properly across multiple modules:

https://github.com/android/nowinandroid/blob/3f7864e0049797f873c6f164391ef915a9682bc1/.github/workflows/AndroidCIWithGmd.yaml#L26

I think it'd be cleanest to run the prerequisite tasks directly, as opposed to depending on a failure, but I'm not sure exactly what those would be. Maybe `packageProdDebugAndroidTest` as one of the last tasks listed in `./gradlew connectedProdDebugAndroidTest --dry-run`?

**Comment by SimonMarquis** [comment]
From my previous tests it seemed GMD already handle this internally and only executes tests after everything is built even when workers are not limited (but I can't confirm this ATM). Also, `packageProdDebugAndroidTest` wasn't a good fit, but I don't remember why exactly...
One solution could also to create Gradle tasks that would trigger the while compilation/assembling but disabling the test execution.

**Comment by SimonMarquis** [comment]
I've tested exactly what you said (`packageProdDebugAndroidTest` and then `connectedProdDebugAndroidTest --dry-run` ) and here is the list of tasks that will have to be executed on the second execution:

```
> Task :app:validateSigningProdDebug
> Task :app:writeProdDebugSigningConfigVersions
> Task :app:writeProdDebugAppMetadata
> Task :app:checkProdDebugDuplicateClasses
> Task :app-nia-catalog:mapProdDebugSourceSetPaths
> Task :app-nia-catalog:createProdDebugCompatibleScreenManifests
> Task :app-nia-catalog:checkProdDebugAarMetadata
> Task :app-nia-catalog:checkProdDebugDuplicateClasses
> Task :app-nia-catalog:writeProdDebugAppMetadata
> Task :app-nia-catalog:validateSigningProdDebug
> Task :app-nia-catalog:writeProdDebugSigningConfigVersions
> Task :app-nia-catalog:processProdDebugResources
> Task :app-nia-catalog:mergeProdDebugJavaResource
> Task :app:mergeProdDebugJavaResource
> Task :app-nia-catalog:packageProdDebug
> Task :app-nia-catalog:createProdDebugApkListingFileRedirect
> Task :app:packageProdDebug
> Task :app:createProdDebugApkListingFileRedirect
```

And if I combine `packageProdDebug packageProdDebugAndroidTest` now only the `connectedAndroidTest` tasks will be executed 👍 
I'll update the following PR with this to get logs:
- #570

**Comment by SimonMarquis** [comment]
The following PR does the same thing for `AndroidCIWithGmd` which should help with build speed:
- https://github.com/android/nowinandroid/pull/695
