### ISSUE TITLE
[FR]: Give the possibility to specify icon colors in the toolbar

### ISSUE THREAD

**Issue by SergeyPinkevich** [android/nowinandroid#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Not a big issue, just a suggestion for improvement :)

For the class `com.google.samples.apps.nowinandroid.core.ui.component.NiaTopAppBar` for `navigationIcon` and `actionIcon` we hardcode the tint color: `tint = MaterialTheme.colorScheme.onSurface`

So, if we would like to specify icon colors for example
```
TopAppBarDefaults.centerAlignedTopAppBarColors(
    actionIconContentColor = Color.White
)
```
it isn't applied since we override this tint color inside the `Icon` class. 

### Describe the solution

So, my suggestion is to remove the tint color from `Icon` and give the possibility to provide specific color outside using the `colors` parameter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
Thanks for the suggestion and apologies for the massive delay in responding. 

`MaterialTheme.colorScheme.onSurface` isn't a hardcoded value. It changes with the user's chosen theme.
