### ISSUE TITLE
[Bug]: Leaking ViewModels

### ISSUE THREAD

**Issue by mahmed1987** [android/nowinandroid#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Reproduction is simple .

Navigation Path
ForYou - Saved (press back)
We correctly see the BookmarkViewModel's onCleared be called

Navigation Path
ForYou - Saved - Interests 
We do not see BookmarksViewModel's onCleared be called in such a position . Not even when we press back on "Interests"

We cannot go back to the Saved Screen , and its ViewModel is still present . 

I realize this is happening because of saveState = true in the popupBuilder. What could be the rationale for that

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hoc081098** [comment]
saveState=true will keep viewmodel until the back stack entry is removed completely 😃
