### ISSUE TITLE
Showing wrong date

### ISSUE THREAD

**Issue by parvinder8** [android/nowinandroid#588]
Article was uploaded on december 2022 but its showing december 2023.

![Screenshot_2023-02-13-09-33-43-196_com google samples apps nowinandroid](https://user-images.githubusercontent.com/107536472/218368681-08886df9-510f-4026-8dc1-d27b3dcdfc2b.jpg)

**Comment by dturner** [comment]
Thanks for spotting this. It's now been fixed on the backend. If you swipe the app away from recents, then restart it, you should see the correct date for that article as the data is resynced.
