### ISSUE TITLE
tho

### ISSUE THREAD

**Issue by thai2551** [android/nowinandroid#601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Page URL (type "NEW" for a new page suggestion)

https://androidonair.withgoogle.com/events/ae-android-13?talk=talk1

### What's the documentation problem or suggestion?

Docs need improving!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rosejr** [comment]
This repository is specifically for the Now in Android app.
