### ISSUE TITLE
[Bug]: KSP apoption does not match \S+=\S+: room.schemaLocation

### ISSUE THREAD

**Issue by rafsanahmad** [android/nowinandroid#604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

While running the project on SImulator or Real device, it is showing error.

Android Studio Electric Eel | 2022.1.1 Patch 1
OS: Mac Ventura 13.2.1

FAILURE: Build failed with an exception.

* What went wrong:

> Configuration cache state could not be cached: field `__options__` of task `:core:database:kspDemoDebugKotlin` of type `com.google.devtools.ksp.gradle.KspTaskJvm`: error writing value of type 'org.gradle.api.internal.provider.DefaultListProperty'

> KSP apoption does not match \S+=\S+: room.schemaLocation=YOUR_PROJECT_DIR/nowinandroid/core/database/schemas

The problem arises from NiaDatabase.kt -> `exportSchema` is set to true. Room generate Database script and save them as JSON file in your local directory.

`AndroidRoomConventionPlugin.kt` -> Configures room schema location to export scheme using `com.google.devtools.ksp`. This plugin is used in build.gradle.kts (Module :core:database)

Line causing the error:

`override fun asArguments() = listOf("room.schemaLocation=${schemaDir.path}")`

**If your project is within a folder that has space in its name, like mine, the Regex is failing as \S+=\S+ does not match in KSP.**

Setting `exportSchema = false` also does not solve the problem. If you give a path in your `schemaDir` which does not contain space, build completes successfully.

can you suggest a proper solution, so it does not depend on whitespace in your schemaDIr.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
This seems like a bug in KSP where "spaces" chars (`\s` in regex) are not supported as arguments. Also, spaces in path are notoriously prone to error in build tools, so my best advice it for you to try moving the project code in a path without spaces.

**Comment by SimonMarquis** [comment]
Here is the corresponding error thrown by KSP:

https://github.com/google/ksp/blob/f3043917af405590e9c8d9422047fb1e3aedfe6e/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt#L161-L163`

We could try to escape spaces with something like, but I'm not sure it's worthy:

```diff
-        override fun asArguments() = listOf("room.schemaLocation=${schemaDir.path}")
+        override fun asArguments() = listOf("room.schemaLocation=${schemaDir.path.replace(" ", "\\ ")}")
```

**Comment by SimonMarquis** [comment]
Or maybe something even simpler:

```diff
-        override fun asArguments() = listOf("room.schemaLocation=${schemaDir.path}")
+        override fun asArguments() = listOf("room.schemaLocation=\"${schemaDir.path}\"")
```

Could you try this on your local machine @rafsanahmad?

**Comment by rafsanahmad** [comment]
Thanks, @SimonMarquis for the suggestion.

 I tried both of the above ways earlier before posting the issue. but still, it failed to build the project giving the same KSP adoption error.
 
 For now, the solution seems to be: move the project to a directory that does not contain space in its path or give a pre-defined path directory without spaces.
 
 `override fun asArguments() = listOf("room.schemaLocation=YOUR_PATH_WITHOUT_SPACE")`

**Comment by RivanParmar** [comment]
I'm also getting the same error on Windows with Android Studio Electric Eel | 2022.1.1

**Comment by abhishekdubey331** [comment]
If I just add 

` override fun asArguments() = listOf("room.schemaLocation=${schemaDir.path.replace(" ","")}")`

It starts to build. We just need to add `replace(" ","")` in `schemaDir.path`.

**Comment by SimonMarquis** [comment]
Since this issue is not direclty related to the project, I think we can close it.
