### ISSUE TITLE
[Bug]: The parent color is getting applied to the child span tag even though it has inline color of its own

### ISSUE THREAD

**Issue by SaiprasadUpshotAi** [android/nowinandroid#606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

I am pass this String as Html text to HtmlCompat class
<span style="color: red">red <span style="color:yellow">yellow</span></span>

but here the first parent span tag "red" is getting red color applied but the child span .i.e. "yellow" is also getting red color applied. But instead it should get yellow color to the text since I am adding style with color yellow. 

Can you guys help me or am I doing something wrong.

Below this the code that i am doing:
         textView.setText(
                HtmlCompat.fromHtml("<span style=\"color: red\">red <span style=\"color:yellow\">yellow</span></span>",HtmlCompat.FROM_HTML_MODE_LEGACY));

here i am creating instance of TextView and adding that view programmatically
![Screenshot_20230221-192537](https://user-images.githubusercontent.com/121153493/220365237-6a85befe-3423-40fd-b0d3-039f30c70af8.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rosejr** [comment]
This issue tracker is specifically for the Now in Android app.
