### ISSUE TITLE
[FR]: Decouple the domain module from the data module

### ISSUE THREAD

**Issue by devjorgecastro** [android/nowinandroid#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I have been working on the Android projects without modulating, and the most normal thing is that by applying Clean Architecture, our **Domain** layer is left without any reference to the **Data** layer. Reviewing the nowinandroid repository, the module of domain (:domain) has data on data (:data), is it possible to decoupling the module :domain totally from :data?

### Describe the solution

I would like to be able to see a dependency investment between **:domain** and **:data** where the contracts (interfaces) of the repositories are in **:domain** and the implementations of these repositories are in **:data**, finally eliminate the reference of **:data** in the module From **domain**. Would it be possible to achieve this using hilt?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
Now in Android follows the official Android guidance so there are no plans to refactor (even on a separate branch as it would add to our maintenance overhead) the domain layer to the "clean architecture" model. That's not to say there aren't benefits to the approach you suggest, just that it's not something we have the bandwidth or the inclination to invest in at the moment. 

Obviously you can create a fork. I would be very interested to see what the dependency graph and implementation looks like.
