### ISSUE TITLE
Why spotless instead of ktlint?

### ISSUE THREAD

**Issue by mobilekosmos** [android/nowinandroid#616]
We are currently using ktlint and automating/rethinking the process around it, since we (Android Devs) see this project as a reference to how to do stuff I have following questions:

1. I wonder why you use spotless instead of ktlint?
2. Your pre-push script seems to run the spotless check over all files despite they were not changed, right?

Btw. suggestion:
pre-push file: "# Usage: Copy this file to your repository's .git/hooks directory. Name it "pre-push" and set the executable bit."
You could automate this with a gradle task.

**Comment by camina-apps** [comment]
https://github.com/android/nowinandroid/discussions
This seems more like a discussion topic rather then an issue, maybe you want to close it and reopen the question in the discussion section?
