### ISSUE TITLE
[FR]: I am a developer from China and need to use the app in order to learn Compose. However, the Google Store is not available in my country.

### ISSUE THREAD

**Issue by Melendez1209** [android/nowinandroid#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I am a developer from China and need to use the app in order to learn Compose. However, the Google Store is not available in my country.

### Describe the solution

I am a developer from China and need to use the app in order to learn Compose. However, the Google Store is not available in my country, is it possible to place an installer in https://developer.android.google.cn/ and provide updates?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
If you are learning Compose, presumably you're using Android Studio. In which case, what's stopping you from building and running the project from there? Wouldn't that be more useful for learning since you have direct access to the source code. 

I'm open to publishing the APK on github but would like to understand your requirements first.

**Comment by superoidlau** [comment]
`nowinandroid` has been installed on my device, when launch the app, can't get data from the network.
I grabbed the log：

![image](https://user-images.githubusercontent.com/13853021/229036533-9800f6c1-6097-49d8-9851-4de2be5dc03f.png)

![image](https://user-images.githubusercontent.com/13853021/229036652-ad267776-396a-41d0-bf93-eb0b4ea825f6.png)

can I use this app in China？and How do I configure it? thanks.

**Comment by superoidlau** [comment]
Ignore above message, I installed `app-demo-release.apk` on device, That's OK.

**Comment by Hackermrj** [comment]
Enable ssl service http: here but you change to https: for protocol
