### ISSUE TITLE
[FR]: Use Gradle type-safe project accessors

### ISSUE THREAD

**Issue by Xsims** [android/nowinandroid#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I discovered in issue #319 that `enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")` has been removed from `build-logic` because it was not being used. 

However, it has never been added to the root project file `settings.gradle.kts`, and as a result, the current code is not robust against naming changes.

```kotlin
dependencies {
    implementation(project(":feature:interests"))
    implementation(project(":feature:foryou"))
    implementation(project(":feature:bookmarks"))
}
```

### Describe the solution

We should introduce `enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")`. This will improve readability and maintainability of the project by using a more consistent way to reference other modules.

With the [gradle type-safe project accessors](https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors), the above code snippet can be replaced with:
```kotlin
dependencies {
    implementation(projects.feature.interests)
    implementation(projects.feature.foryou)
    implementation(projects.feature.bookmarks)
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
Thanks for raising this. Type safe project accessors were enabled in #958.
