### ISSUE TITLE
[Cleanup] Remove suppression for plugin applications with alias once updated to Gradle 8.1

### ISSUE THREAD

**Issue by alexvanyo** [android/nowinandroid#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

#35 added suppression for using the `alias` to apply plugins from `libs.versions.toml`.

In Gradle 8.1, this workaround is no longer necessary: https://docs.gradle.org/8.1-rc-1/userguide/upgrading_version_8.html#kotlin_dsl_plugins_catalogs_workaround

Once we update to Gradle 8.1, we'll be able to remove those suppressions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AnirudhPudari** [comment]
@alexvanyo Hi, Can i take this issue, i will make these changes once you guys update to Gradle 8.1.

**Comment by alexvanyo** [comment]
Definitely, happy to review a PR once we've updated to Gradle 8.1
