### ISSUE TITLE
[Bug]: Update to AGP 8.0

### ISSUE THREAD

**Issue by alexvanyo** [android/nowinandroid#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

AGP 8.0 is stable with Android Studio Flamingo, so we should update our dependencies to it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akingyin1987** [comment]
me too
