### ISSUE TITLE
`TopAppBar` glitch during navigation

### ISSUE THREAD

**Issue by SimonMarquis** [android/nowinandroid#721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

The `TopAppBar` disappears before the navigation completes, leading to a UI glitch and layout shifting.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

https://github.com/android/nowinandroid/assets/1921278/63e38896-fb03-4554-a4a4-6a4dbfedc9a9

![screen-20230510-112651_exported_609.jpg](https://github.com/android/nowinandroid/assets/1921278/90fefafe-2af0-416c-88c8-9f15baa5a45f)

**Comment by abalros** [comment]
في أربعاء، 10 مايو، 2023 في 1:10 م، كتب Simon Marquis <
***@***.***>:

**Comment by TusharBhatia34** [comment]
hello can i work on this?

**Comment by TusharBhatia34** [comment]
hey is it still open? can you assign me this issue

**Comment by trambui09** [comment]
Closing this, please re-open if it's still an issue
