### ISSUE TITLE
[Bug]: Impossible to sync the project with embedded java of Android Studio Flamingo

### ISSUE THREAD

**Issue by FabienSe** [android/nowinandroid#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

I have Android Studio Flamingo | 2022.2.1 Patch 1 which is shipped with JDK 17.

With changes provided by https://github.com/android/nowinandroid/pull/583, the synchronization of the project fails with `No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}.`

Seems like I would need to install a separate instance of Java to also have JDK 11 installed on my computer which is annoying.

It is possible to configure the jvmTarget without requiring a specific toolchain, this way the project can be compiled with the embedded version of Java which is JDK 17.

### Relevant logcat output

```shell
Failed to calculate the value of task ':core:model:compileJava' property 'javaCompiler'.
No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}.
No locally installed toolchains match (see https://docs.gradle.org/8.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1/userguide/toolchains.html#sub:download_repositories).
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stef-ang** [comment]
I got same problem. I thought updating to Android Studio Flamingo would fix AGP 8.0.0 issue, but then I got another issue

**Comment by digrec** [comment]
Same bug here.

```
Failed to calculate the value of task ':core:model:compileJava' property 'javaCompiler'.
No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}.
No locally installed toolchains match (see https://docs.gradle.org/8.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1/userguide/toolchains.html#sub:download_repositories).
```

```
Android Studio Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 19, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false
    gradle.version.catalogs.dynamic.support=true

Non-Bundled Plugins:
    com.github.lppedd.idea-conventional-commit (0.22.0)
    com.developerphil.adbidea (1.6.9)
```

Pretty lame bug when you have such statement in the README:

> Now in Android uses the Gradle build system and can be imported directly into Android Studio (make sure you are using the latest stable version available [here](https://developer.android.com/studio)).

**Comment by alexvanyo** [comment]
This should be fixed now, please leave another comment if you're still running into this issue syncing with Flamingo.

**Comment by digrec** [comment]
@alexvanyo it works. Thanks for the quick fix!
