### ISSUE TITLE
[Bug]: use @Upsert get java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/room/EntityUpsertionAdapter;

### ISSUE THREAD

**Issue by ggyypp** [android/nowinandroid#734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

@Upsert get error :java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/room/EntityUpsertionAdapter;

but others work, like :@Insert @Update 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
@ggyypp can you provide the full stacktrace of the error and the steps you took to reproduce it?
