### ISSUE TITLE
Can't seem to load app data

### ISSUE THREAD

**Issue by KenjiPcx** [android/nowinandroid#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

I downloaded the app from the app store, but it doesn't seem to be loading the assets for me, anyone had this issue?

![Screenshot_20230529_172912_Now in Android](https://github.com/android/nowinandroid/assets/56083944/79365878-24dc-4d2d-9178-f6140fdbb056)

![Screenshot_20230529_172917_Now in Android](https://github.com/android/nowinandroid/assets/56083944/4e4868ca-558b-4b1d-9ddd-60dd148cf2e8)

Device info:
OS: Android 13 One UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tunjid** [comment]
Hi @KenjiPcx this should be fixed now, just restart the app and the data should be present.

**Comment by KenjiPcx** [comment]
Nice! can confirm on my end, it works now
