### ISSUE TITLE
[Bug]: The colour of the bottom navbar Icon doesn't change after changing the theme.

### ISSUE THREAD

**Issue by imranaai** [android/nowinandroid#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

When we change the theme from Dynamic colour to normal or other way around the colour of the bottom navbar Icon doesn't change until we touch on a different navbar icon.

https://github.com/android/nowinandroid/assets/112740592/d553f168-1554-4295-8dab-8b4821c050d9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
Is this using the current Play Store version of the app?

If so, I think this is #422, which is fixed with the latest version of the code.

**Comment by imranaai** [comment]
> Is this using the current Play Store version of the app?
> 
> If so, I think this is #422, which is fixed with the latest version of the code.

Hi, I am new to Open Source, please let me know if you want to say that this has been fixed but waiting to be rolled out in the Play Store.

Because I have the latest play store version and I see the same issue.

**Comment by alexvanyo** [comment]
Yes that's exactly right, it's been fixed in the repo but the fix hasn't rolled out to the Play Store yet.

Thank you for reporting the issue and following up!
