### ISSUE TITLE
[Feature request]: Different icons for each build variant

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#800]
When developing Now in Android, you can often find yourself building and testing different build variants. This leads to multiple installs of the app, but no way of distinguishing between them. 

![image](https://github.com/android/nowinandroid/assets/873212/7a958b95-a856-44a8-8c1f-8ab57355e8c6)

It'd be great to have different icons based on the build type. Perhaps different background colours, different android logo colours, or a different symbol inside the brackets.

**Comment by dturner** [comment]
The icon design assets are here: https://www.figma.com/file/UamSYTeJg2ZGqC9k7jiGt1/Now-In-Android-Case-Study-(Community)?type=design&node-id=49-15740&t=QAkFq6Q6fVBx390t-0

**Comment by dturner** [comment]
Yes, sorry, link updated

**Comment by SimonMarquis** [comment]
Thanks for the update link.
Having different colors for each variant is probably the simplest solution here, as we are using AVDs.
Bages and ribbons would force us to create either more complex svg, or fallback to pngs.

As you said, we could change the background color. Or maybe, we could do the other way around.
My reasoning is that changing the icons color (the droid and/or the curly braces) would be more subtle that painting the background. And it would still support dark/light themes without being too "bold".

**Comment by SimonMarquis** [comment]
Did you had someting in mind regarding a potential color mapping?

Here is what it could look like (background vs foregroud):

<img src="https://github.com/android/nowinandroid/assets/1921278/56e19dbf-0889-45c4-b270-630e5926370b" width="400">
