### ISSUE TITLE
[Bug]: Build fails on 2021.3.1 Patch 1

### ISSUE THREAD

**Issue by jshroff** [android/nowinandroid#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

build fails with the following error

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':app:classpath'.
      > Could not resolve project :build-logic:convention.
        Required by:
            project :app
         > No matching variant of project :build-logic:convention was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.1' but:
             - Variant 'apiElements' capability com.google.samples.apps.nowinandroid.buildlogic:convention:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.1')
             - Variant 'mainSourceElements' capability com.google.samples.apps.nowinandroid.buildlogic:convention:unspecified declares a component, and its dependencies declared externally:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java version (required compatibility with Java 11)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.1')
                     - Doesn't say anything about its usage (required runtime)
             - Variant 'runtimeElements' capability com.google.samples.apps.nowinandroid.buildlogic:convention:unspecified declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.1')
             - Variant 'testResultsElementsForTest' capability com.google.samples.apps.nowinandroid.buildlogic:convention:unspecified:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                     - Doesn't say anything about its target Java version (required compatibility with Java 11)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.1')
                     - Doesn't say anything about its usage (required runtime)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
Which version of the JDK are you using?

[AGP 8.0 requires JDK 17 or later](https://developer.android.com/build/releases/gradle-plugin#jdk-17-agp), it looks like maybe you are using JDK 11?

**Comment by jshroff** [comment]
@alexvanyo thanks for looking into this - yes I am using Android Studio Dolphin - will update to Flamingo (Apparently that bundles JDK 17)
