### ISSUE TITLE
[FR]: Allow localised date format

### ISSUE THREAD

**Issue by mvescovo** [android/nowinandroid#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Hi. I noticed that for some reason this app hard codes the date format in the "NewsResourceCard" instead of using the user defined Locale.
        
I think it's better to let the user choose the format rather than the developer.

Thanks.

### Describe the solution

In the "NewsResourceCard" use  

```
 return DateTimeFormatter
        .ofLocalizedDate(MEDIUM)
        .withLocale(Locale.getDefault())
        .withZone(zoneId)
        .format(publishDate.toJavaInstant())
```

instead of 

```
    return DateTimeFormatter
        .ofPattern("MMM d, yyyy")
        .withZone(zoneId)
        .format(publishDate.toJavaInstant())
```

I tested this locally and it seems to work fine so I'm not sure why it was ever hard coded. Curious to know if there's some issue with allowing the user defined Locale, or if maybe I'm not understanding something such that once understood would also lead me to want to hard code the format.

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
This issue is now fixed and can be close @mvescovo
