### ISSUE TITLE
[Bug]: ksp-gradlePlugin in libs.versions.toml

### ISSUE THREAD

**Issue by ELOVSKIY** [android/nowinandroid#841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

ksp-gradlePlugin property  has wrong  attribute name in libs.versions.toml.

`ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }` but shopuld be `ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "gradle.plugin", version.ref = "ksp" }`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
Where did you find this dependency name?
From maven metadata it seems like the current name is the right one: https://mvnrepository.com/artifact/com.google.devtools.ksp/com.google.devtools.ksp.gradle.plugin

**Comment by ELOVSKIY** [comment]
See, strange format for dependency name.  My bad, thank you for link.
