### ISSUE TITLE
[Bug] Tapping on a topic chip doesn't open the topic detail screen

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#865]
Version tested: 0.1.2

Steps to repro: 

- Open the For You screen
- Tap on any topic chip

Expected result

- Topic detail screen for that topic is shown

Actual result

- Nothing happens, although the tap animation is shown

Other notes
If you bookmark a new resource, then open the Saved screen, then tap on the topic chip there, it does work as expected.

**Comment by SimonMarquis** [comment]
Probably related to this line

https://github.com/android/nowinandroid/blob/cd2fbb02b6c7d76e652f7adf2e443bf0de11ec1a/app/src/main/java/com/google/samples/apps/nowinandroid/navigation/NiaNavHost.kt#L52
