### ISSUE TITLE
[Bug]: Screen goes blank when rapidly switch back and forth between two screens multiple times

### ISSUE THREAD

**Issue by anilbeesetti** [android/nowinandroid#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

When I rapidly switch back and forth between two screens multiple times, the screen eventually goes blank after a few clicks. This problem occurs within the [`NextPlayer`](https://github.com/anilbeesetti/nextplayer) app, usually after around 10 clicks. Interestingly, when I tested a similar scenario in `Now in android` app, it required many more taps before the screen went blank. Can someone help me figure out this issue

Checkout the following screen recordings for reference

https://github.com/android/nowinandroid/assets/66936649/e0715994-3e3f-485a-a8a1-5d7851ab9f8b

https://github.com/android/nowinandroid/assets/66936649/4f507cd5-7ec7-4424-af11-a911ef9c2a87

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Victor-Agbo** [comment]
Can you provide your Android version?
I don't seem to be able to reproduce the issue with the steps in the screen record.

**Comment by anilbeesetti** [comment]
@Victor-Agbo I've tested this on android 11 and 13 and this problem exists. But I kinda solved this problem by using navigateUp instead of popBackStack. Here's some more info on fix https://github.com/anilbeesetti/nextplayer/pull/511
