### ISSUE TITLE
[Bug]: Issue while running ./gradlew build

### ISSUE THREAD

**Issue by er-abhishek-luthra** [android/nowinandroid#910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Issue while running ./gradlew build 
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':app:classpath'.
      > Could not resolve project :build-logic:convention.
        Required by:
            project :app
         > No matching variant of project :build-logic:convention was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.2' but:
             - Variant 'apiElements' capability com.tandroosti.eua.buildlogic:convention:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11

### Relevant logcat output

```shell
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':app:classpath'.
      > Could not resolve project :build-logic:convention.
        Required by:
            project :app
         > No matching variant of project :build-logic:convention was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.2' but:
             - Variant 'apiElements' capability com.tandroosti.eua.buildlogic:convention:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
The logs you give us are the raw logs of the build.
But, if you run this from Android Studio, it will show up this message:

```
Gradle JVM version incompatible.
This project is configured to use an older Gradle JVM that supports up to version 11 but the current AGP requires a Gradle JVM that supports version 17.

Change Gradle JDK...
See AGP Release Notes...
```

And the last two lines are links to configure the JDK.

---

That being said, we could override this behavior and force checking for the appropriate version:

```kotlin
if (JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_17).not()) {
    throw GradleException(
        """
        Now in Android requires JDK 17 but it is currently using JDK ${JavaVersion.current()}.
        Java Home: [${System.getProperty("java.home")}]
        """.trimIndent()
    )
}
```

WDYT?

**Comment by dturner** [comment]
Agree with your suggested fix @SimonMarquis. Only thing I would add is that the message should also provide a solution (e.g., https://github.com/android/nowinandroid/issues/1137#issuecomment-2392829757).

Feel free to submit a PR.

**Comment by SimonMarquis** [comment]
I feel like the fix should not be to manually edit config files, but instead to use the Android Studio UI (`File | Settings | Build, Execution, Deployment | Build Tools | Gradle`) that will make sure the proper JDK is selected and configured in the right file:

https://developer.android.com/build/jdks and more precisely this https://developer.android.com/build/jdks#jdk-config-in-studio

![image](https://github.com/user-attachments/assets/5483ea0b-b4e7-48f3-8087-436abcf5393b)

**Comment by dturner** [comment]
Sounds good to me. Just use that link in the error description.
