### ISSUE TITLE
[Bug]: about #868，I found two bugs

### ISSUE THREAD

**Issue by lelelongwang** [android/nowinandroid#920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### about #868，I found two bugs:

- bug 1: When you execute onTopicClick in foryouScreen to enter the topicScreen, and then click foryouItem on the navigationbaritem, you cannot jump to foryouScreen.

> Solution 1: It can be consistent with "Interests", when jumping from foryouScreen to topicScreen, "Foryou" is still selected

> Solution 2: After jumping from foryouScreen to topicScreen, if "Interests" is selected, clicking "Foryou" should enter foryouScreen

- bug 2: When I execute onTopicClick again in topicScreen, I do not enter the new topicScreen according to the new topic ID, which means that in the topicScreen interface, the onTopicClick interface does not change

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
Fixed in #1681
