### ISSUE TITLE
[Bug]: Getting RESULT_CODE_PROFILE_ENQUEUED_FOR_COMPILATION when App is Installed via Play Store

### ISSUE THREAD

**Issue by dhruvkaushal11** [android/nowinandroid#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

A bug happened!Hi Team,
We have implemented Baseline Profiles, I can also see baseline files assets/dexopt/baseline.prof in the APK.

After uploading and installing app from Play Store Internal Track I am getting result of ProfileVerifier.getCompilationStatusAsync().get() as RESULT_CODE_PROFILE_ENQUEUED_FOR_COMPILATION(2) instead of RESULT_CODE_COMPILED_WITH_PROFILE(1)

As per the NowInAndroid documentation it says "When delivering through Google Play, the baseline profile is compiled during installation. In this case you will see the correct state logged without any further action necessary. To verify baseline profile installation locally, you need to manually trigger baseline profile installation"

But then this is not happening for Play Installed build until i run adb shell cmd package compile -f -m speed-profile com.example

Source for Above Documentation:
https://github.com/android/nowinandroid/blob/main/app/src/main/java/com/google/samples/apps/nowinandroid/MainActivity.kt

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
I tried on my device (Pixel 6 Pro) and it correctly got these logs after installing from the Google Play Store:

```
09-14 20:00:45.194 11708 11899 D ProfileInstaller: Installing profile for com.google.samples.apps.nowinandroid
09-14 20:00:45.215 11708 11851 D MainActivity: ProfileInstaller status code: 1
09-14 20:00:45.215 11708 11851 D MainActivity: ProfileInstaller: is compiled with profile
09-14 20:00:45.215 11708 11781 D MainActivity: ProfileInstaller status code: 1
09-14 20:00:45.215 11708 11781 D MainActivity: ProfileInstaller: is compiled with profile
```

(although for whatever reason, the last 2 logs were duplicated)

**Comment by SimonMarquis** [comment]
If what your are seeing is not related to the Now in Android app but one of your personal app, it might not be the best place to post this kind of issue here.
Maybe try asking on the [discussions tab](https://github.com/android/nowinandroid/discussions), but again, this project is not supposed to be a troubleshooting guide 😉

That being said, you might have forgot to configure something. Make sure to follow the official baseline profile documentation on https://developer.android.com/topic/performance/baselineprofiles/overview to properly set up baseline profile on your own app.

**Comment by dhruvkaushal11** [comment]
Please Google Team, start testing on non Pixel devices. This all works well on Pixel devices only.

**Comment by soumenpauljar** [comment]
Hey @dhruvkaushal11 , Did you find any solutions for this? We are facing the same issue also.
