### ISSUE TITLE
Can we copy this nowinandroid code and customise it according to my own app.

### ISSUE THREAD

**Issue by vballem** [android/nowinandroid#967]
I see that nowinAndroidApp has all the best practices and has many generic common modules like database, restapi, connectivitystatus and preferences for an app to be developed from scratch in compose now a days. Instead of re-inventing the wheel, Can I copy and customise according to my own application needs?
 
If Yes, What I should not change?.

**Comment by Spirarel** [comment]
There's an [Apache 2.0 license](https://github.com/android/nowinandroid/blob/main/LICENSE) on the project. You'd have to follow up all the dependencies to verify if their licenses permit your use-case.

**Comment by vballem** [comment]
Thanks for your prompt response @Spirarel .
