### ISSUE TITLE
[Bug]: Dex Layout reordering requires non-minified benchmark build

### ISSUE THREAD

**Issue by keyboardsurfer** [android/nowinandroid#992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

We can enable Dex layout reordering to use startup profiles. To use them, the benchmark build needs to have `isMinifyEnabled = false`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vatsasiddhartha** [comment]
Can you specify the issue more ...

**Comment by SimonMarquis** [comment]
+1 Can you explain what "Dex layout reordering" is? I found nothing while search for these terms.
Is it an automated AGP process? Or a hidden configuration?

**Comment by lihenggui** [comment]
> +1 Can you explain what "Dex layout reordering" is? I found nothing while search for these terms. Is it an automated AGP process? Or a hidden configuration?

I guess it is `DEX layout optimizations`

https://developer.android.com/topic/performance/baselineprofiles/dex-layout-optimizations#dex-layout-optimizations

**Comment by priyanshnama** [comment]
can i pick this up

**Comment by keyboardsurfer** [comment]
Thanks @priyanshnama. With already #1020 in flight to address this issue there is no need for another approach at this time.

**Comment by keyboardsurfer** [comment]
The switch to not use a specific build type but rely on the Baseline Profile Gradle plugin to provide the right build type makes this bug obsolete.
