### ISSUE TITLE
[Bug]: `Build` workflows remained queued

### ISSUE THREAD

**Issue by SimonMarquis** [android/nowinandroid#993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

[`Build` workflows](https://github.com/android/nowinandroid/actions/workflows/Build.yaml?query=is%3Aqueued) remained in the `queued` state since yesterday.

- [GitHub status](https://www.githubstatus.com/) is ok 🟢
- [`Build` workflows from forks](https://github.com/SimonMarquis/nowinandroid/actions/workflows/Build.yaml) are ok 🟢 

Did something changed in the repository configuration?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
Thanks for reporting this. I've cancelled all the queued jobs and restarted one of them. Hopefully this is just a temporary outage on github actions.

**Comment by dturner** [comment]
Seems like this was a GitHub issue (despite it not being reported on the status page). Restarting/deleting the queued jobs seems to have fixed it.
